export const APP_THEME = 'APP_THEME';

export const CHECK_FILTER_CELL = "CHECK_FILTER_CELL"
export const CATEGORY = "CATEGORY"
//Api type
export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const API_ERROR = 'API_ERROR';

//Otp Action
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

//Email Oyt Action
export const VERIFY_EMAIL_OTP_SUCCESS = 'VERIFY_EMAIL_OTP_SUCCESS';
export const VERIFY_EMAIL_OTP_FAILURE = 'VERIFY_EMAIL_OTP_FAILURE';

//Categories
export const SAVE_ALL_CATEGORIES = 'SAVE_ALL_CATEGORIES';
export const SAVE_SUB_CATEGORY_INDEX = 'SAVE_SUB_CATEGORY_INDEX';
export const SAVE_PRODUCT_LIST = 'SAVE_PRODUCT_LIST';

//Logout
export const USER_LOGOUT = 'USER_LOGOUT';

// Skip Login Actions
export const ROUTE_TO_REDIRECT_AFTER_SKIP_SIGNIN = 'ROUTE_TO_REDIRECT_AFTER_SKIP_SIGNIN'

// CITYMAX actions
export const SAVE_FRP_PRODUCT_LIST = 'SAVE_FRP_PRODUCT_LIST'
export const SAVE_FRP_PRODUCT_DETAIL = 'SAVE_FRP_PRODUCT_DETAIL'

//Documents
export const CHANGE_DOCUMENT_POSITION = "CHANGE_DOCUMENT_POSITION"
export const SAVE_KYC_DOCUMENT_DETAIL = "SAVE_KYC_DOCUMENT_DETAIL"

//Address 
export const CHANGE_ADDRESS_POSITION = "CHANGE_ADDRESS_POSITION"
export const SET_ADDRESS_LIST = "SET_ADDRESS_LIST"

// CF Coins
export const GET_CREDIT_DETAIL = "GET_CREDIT_DETAIL"
export const GET_DEBIT_DETAIL = "GET_DEBIT_DETAIL"

// Cart badge action
export const UPDATE_CART_BADGE_COUNT = "UPDATE_CART_BADGE_COUNT"


// Wishlist badge action
export const UPDATE_WISHLIST_BADGE_COUNT = "UPDATE_WISHLIST_BADGE_COUNT"