const images = {
  
  icn_show_password: require('./icons/password/eye.png'),
  icn_hide_password: require('./icons/password/hide.png'),
  icn_back: require('./icons/backButton/backCopy.png'),
  icn_close: require('./icons/sortFilter/closeIcon/close.png'),
  icn_roundchecked: require('./icons/sortFilter/checkedIcon/checked.png'),
  icn_roundCheck: require('./icons/sortFilter/unChecked/check.png'),
  img_logo: require('./appLogo/logo.png'),
  img_new_logo: require('./final-logo.png'),
  img_fb: require('./imagesSocial/facebook.png'),
  img_google: require('./imagesSocial/googlePlus.png'),
  img_linkedin: require('./imagesSocial/linkedin.png'),
  splash_background: require('./splash/city.png'),
  splash_btnIcon: require('./splash/btnIcon.png'),
  splash_right: require('./splash/right.png'),

  splash_v6icon: require('./splash/v6-icon.png'),
  splash_shippingIcon: require('./splash/shippingIcon.png'),
  splash_setting: require('./splash/setting.png'),
  splash_cardMainImage: require('./splash/cardMainImage.png'),
  

  close_white_icn: require('./filter/close.png'),
  navigation_icn: require('./icons/navigation/navigation.png'),
  addButton: require('./icons/addButton.png'),
  c1: require('./icons/c1.png'),
  c2: require('./icons/c2.png'),
  
  referral_background: require('./referral/referralCode.png'),
  referral_back : require('./referral/refferfrd.png'),
  coins_icn: require('./referral/coins.png'),
  red_heart_icn: require('./icons/heart/redHeart.png'),
  kyc_icn: require('./productDetail/kycIcon.png'),
  delivery_icn: require('./productDetail/deliveryIcon.png'),
  quality_icn: require('./productDetail/qualityIcon.png'),
  forward_icn: require('./icons/arrow/forwardArrow.png'),
  icn_home: require('./tab/home/home.png'),
  icn_home_selected: require('./tab/homeSelected/home.png'),
  icn_search: require('./tab/search/search.png'),
  icn_search_Selected: require('./tab/searchSelected/search.png'),
  icn_wishlist_Select: require('./tab/wishlistSelected/wishlist.png'),
  icn_wishlist: require('./tab/wishlist/wishlist.png'),
  icn_category: require('./tab/category/category.png'),
  icn_category_select: require('./tab/categorySelected/category.png'),
  icn_cart: require('./tab/cart/cart.png'),
  icn_cart_Selected: require('./tab/cartSelected/cart.png'),
  icn_menu: require('./icons/menu.png'),
  img_avtar: require('./icons/avtar.png'),
  img_delete: require('./icons/bin.png'),
  icn_filter: require('./icons/filter.png'),
  icn_sort: require('./icons/sort.png'),
  icn_back_white: require('./icons/arrow/back.png'),
  icn_share: require('./productDetail/share.png'),
  icn_share1: require('./productDetail/share1.png'),
  TestimonlalsSection : require('./productDetail/TestimonlalsSection.png'),
  icn_white_heart: require('./productDetail/icn_white_heart.png'),
  icn_selectedsaqure: require('./filter/checkboxSqure/checked.png'),
  icn_unSelectedSqure: require('./filter/checkboxSqure/check.png'),
  img_placeholer_small: require('./placeholders/image.png'),
  img_placeholer_large: require('./placeholders/placeholder.png'),
  inc_appLogo_header: require('./appLogo/appLogo.png'),
  icn_Plus: require('./icons/plus7.png'),
  icn_tickInvoices: require('./icons/Bitmap.png'),
  icn_Minus: require('./icons/minus4.png'),
  cf_coins: require('./icons/coins.png'),
  inc_small_cross: require('./cart/smallCross.png'),
  inc_small_delete: require('./cart/deleteNew.png'),
  inc_small_pin: require('./cart/pin.png'),
  inc_small_tag: require('./cart/Tag.png'),
  inc_small_all: require('./cart/kyc.png'),
  inc_small_freecan: require('./cart/freecan.png'),
  inc_small_freeins: require('./cart/freeins.png'),
  inc_small_allpro: require('./cart/allpro.png'),
  inc_small_internal: require('./cart/internal.png'),
  inc_small_orderplace: require('./cart/orderplace.png'),
  inc_small_emi: require('./cart/emi.png'),
  inc_offers : require('./cart/offer.png'),
  inc_coin : require('./cart/coin.png'),
  inc_coin1 : require('./cart/coin1.png'),
  inc_paymentoffer : require('./cart/paymentoffer.png'),
  inc_right_arrow: require('./icons/arrow/rightArrow.png'),
  icn_search_items: require('./icons/search_new.png'),
  icn_coin: require('./myAccount/coinn.png'),
  icn_listIcon: require('./myAccount/listIcon.png'),
  icn_kycPending: require('./myAccount/kycPending.png'),
  icn_homePageView: require('./myAccount/homePageView.png'),
  icon_nullsearch : require('./myAccount/serchEmoji.png'),
  icn_cancelCard : require("./myAccount/cancellation.png"),
  icn_bedroom : require("./myAccount/bedroom.png"),
  icn_searchPage : require("./myAccount/search.png"),
  icn_cartPage : require("./myAccount/cart.png"),
  icn_pending : require("./myAccount/cancellation.png"),
  icn_complate : require("./myAccount/pending.png"),
  icon_whatapps : require("./myAccount/whatapps.png"),
  icon_hairLine : require("./myAccount/hairLine.png"),
  icon_rightA : require("./myAccount/rightA.png"),
  icon_leftA : require("./myAccount/leftA.png"),
  icn_referral_code: require('./myAccount/referafrd.png'),
  icn_referral_codefrd: require('./myAccount/hevefrd.png'),
  icn_address: require('./myAccount/adderess.png'),
  icn_invoice: require('./myAccount/invoices.png'),
  icn_documents: require('./myAccount/documents.png'),
  icn_chat: require('./myAccount/chat.png'),
  icn_order: require('./myAccount/myorder2.png'),
  icn_payments: require('./myAccount/mycart2.png'),
  icn_auto_payments: require('./myAccount/autopay.png'),
  icn_password: require('./myAccount/password.png'),
  icn_profile_setting: require('./myAccount/profilenew.png'),
  icn_profile_arrow: require('./myAccount/right.png'),
  icn_profile_verified: require('./myAccount/verified.png'),
  icn_profile_logout: require('./myAccount/logout.png'),
  icn_logout: require('./myAccount/logoutIcon.png'),
  icn_skip: require('./myAccount/skip.png'),
  icn_dot1: require('./myAccount/1Dot.png'),
  icn_dot2: require('./myAccount/2Dot.png'),
  icn_dot3: require('./myAccount/3Dot.png'),
  icn_slideframe: require('./myAccount/slideframe.png'),
  icn_step2: require('./myAccount/step2.png'),
  icn_step1: require('./myAccount/step1.png'),
  icn_step3: require('./myAccount/step3.png'),
  icn_installation: require('./cart/installation.png'),
  icn_upgrade: require('./cart/upgrade.png'),
  icn_relocation: require('./cart/relocation.png'),
  icn_damage: require('./cart/damage.png'),
  pin_green : require('./cart/pin_green.png'),
  icn_HelpLine: require('./order/bitmap.png'),
  img_right_icon : require('./cart/right.png'),

  icn_amountPaid: require('./order/amountPaid.png'),
  icn_order: require('./order/order.png'),
  icn_rent: require('./order/rent.png'),
  icn_shipping: require('./order/shipping.png'),

  img_Benefit1: require('./benefits/image.png'),
  img_Benefit2: require('./benefits/image0.png'),
  img_Benefit3: require('./benefits/image1.png'),
  img_Benefit4: require('./benefits/image4.png'),
  img_Benefit5: require('./benefits/image5.png'),
  img_Benefit6: require('./benefits/image2.png'),
  img_thumnail_white: require('./order/iconColor.png'),
  icn_copy: require('./benefits/copy.png'),
  img_line: require('./line.png'),
  icn_checkout: require('./cfCoins/checkout1.png'),
  icn_benefits: require('./cfCoins/benefits1.png'),
  icn_card: require('./cfCoins/card.png'),
  icn_wallet: require('./cfCoins/wallet.png'),
  icn_phone: require('./contactUs/customerService1.png'),
  icn_services: require('./contactUs/support3.png'),
  icn_email: require('./contactUs/email10.png'),
  bg_voucher: require('./offers/BG.png'),
  img_discount: require('./offers/Discount.png'),
  icn_done_status: require('./order/roundedCheckbox.png'),
  icn_pending_status: require('./order/ovalPending.png'),
  icn_process_status: require('./order/ovalCopy.png'),
  img_dash_line: require('./frp/dashLine.png'),
  img_backicon: require('./frp/backIcon.png'),
  size_icon : require('./frp/size.png'),
  close_icon : require('./frp/close.png'),
  icn_truck: require('./cart/truck.png'),
  img_Step1: require('./howitworks/01.png'),
  img_Step2: require('./howitworks/02.png'),
  img_Step3: require('./howitworks/03.png'),
  img_Step4: require('./howitworks/04.png'),
  img_Step5: require('./howitworks/05.png'),
  img_Step6: require('./howitworks/06.png'),
  img_slider_thumb: require('./frp/oval.png'),
  icn_large_coins: require('./creditScore/coins.png'),
  icn_drop_down: require('./creditScore/drpoDown.png'),
  img_refer_a_friend: require('./referral/bg.png'),
  icn_document_done: require('./documentation/roundedCheckbox.png'),
  icn_button_icon: require('./documentation/letftArrow.png'),
  icn_document_pending: require('./documentation/ovalCopy.png'),
  img_upload: require('./documentation/shape.png'),
  upload: require('./documentation/upload.png'),
  img_DropDown: require('./documentation/polygonCopy.png'),
  img_empty_cart: require('./cart/cart.png'),
  img_zero: require('./documentation/zero.png'),
  icn_pdf: require('./icons/pdf.png'),
  icn_info: require('./icons/info.png'),
  icn_addressDelete: require('./icons/editAddress/delete.png'),
  icn_addressEdit: require('./icons/editAddress/edit.png'),
  icn_netbanking: require('./cfCoins/netbanking.png'),
  img_homeBg: require('./home/homebg.png'),
  icn_whatsapp: require('./icons/whatsapp.png'),
  icn_contactUs: require('./icons/contact.png'),
  icn_notification: require('./icons/notification.png'),
  icn_customerPayment: require('./icons/customerPayment.png'),
  icn_capitalExpenditure: require('./icons/capitalExpenditure.png'),
  icn_faQs: require('./icons/faQs.png'),
  icn_howItWorks: require('./icons/howItWorks.png'),
  icn_kycDocuments: require('./myAccount/document.png'),
  icn_searchimg: require('./icons/searchimg.png'),
  icn_wishlistimg: require('./icons/wishlist.png'),
  icn_emptyInvoice: require('./icons/emptyInvoice.png'),
  icn_emptyPayment: require('./icons/emptyPayment.png'),
  img_Step1_coin: require('./howitworks/cfReg.png'),
  img_Step2_coin: require('./howitworks/share8.png'),
  img_Step3_coin: require('./howitworks/refCode.png'),
  img_Step4_coin: require('./howitworks/cfCoine.png'),
  img_Step5_coin: require('./howitworks/futurePayment.png'),
  icn_cartProduct: require('./icons/cartP.png'),
  img_no_products_found: require('./icons/no_products_found.png'),
  img_no_service_found: require('./icons/serviceRequest.png'),
  img_no_order_found: require('./order/emptyOrder.png'),
  img_no_address_found: require('./icons/noaddress.png'),
  img_Intro1: require('./introSlider/001.png'),
  img_Intro2: require('./introSlider/002.png'),
  img_Intro3: require('./introSlider/003.png'),
  img_Intro4: require('./introSlider/004.png'),
  img_Intro5: require('./introSlider/005.png'),
  img_safety01: require('./safety/Delivery-Icon.png'),
  img_safety02: require('./safety/Sanitised-Furniture.png'),
  img_safety03: require('./safety/Safety-Checks.png'),
  img_safety04: require('./safety/Hygiene-Delivery-Pickup.png'),
  img_safety05: require('./safety/Contact-Tracing.png'),
  img_profit01: require('./profits/01.png'),
  img_profit02: require('./profits/02.png'),
  img_profit03: require('./profits/03.png'),
  img_profit04: require('./profits/04.png'),
  img_profit05: require('./profits/05.png'),
  img_profit06: require('./profits/06.png'),
  house: require('./documentation/home.png'),
  success: require('./documentation/success.png'),
  reload: require('./documentation/reload.png'),
  delete: require('./documentation/delete.png'),
  sample_product: require('./productDetail/sample_product.png'),
  upgrade: require('./order/upgrade.png'),
  relocation: require('./order/relocation.png'),
  extend_tenure: require('./order/extend_tenure.png'),
  order_pickup: require('./order/order_pickup.png'),
  installation: require('./order/installation.png'),
  repair: require('./order/repair.png'),
  transfer_owner: require('./order/transfer_owner.png'),
  buy: require('./order/buy.png'),
  cancel: require('./order/cancel.png'),
  check: require('./order/check.png'),
  uncheck: require('./order/uncheck.png'),
  img_shield: require('./cart/shield.png'),
  img_percent: require('./cart/percentage.png'),
  img_star: require('./cart/star.png'),
  img_dot_line: require('./cart/dot_line.png'),
  img_ellipse_left: require('./cart/ellipse_left.png'),
  img_ellipse_right: require('./cart/ellipse_right.png'),
  img_whatsapp: require('./cart/whatsapp.png'),
  img_arrow_down: require('./cart/arrow_down.png'),
  img_water: require('./cart/water.png'),
  img_house_break: require('./cart/house_break.png'),
  img_glass_break: require('./cart/glass_break.png'),
  img_crack: require('./cart/crack.png'),
  img_clear_offer: require('./cart/clear_offer.png'),
  img_house_outline: require('./cart/house_outline.png'),
};
export default images;
