const events = {
    MOVE_TO_CART: 'MOVE_TO_CART',
    ON_CHANGE_CITY:'ON_CHANGE_CITY',
    UPDATE_CATEGORY_SCREEN_PRODUCT_LIST:'UPDATE_CATEGORY_SCREEN_PRODUCT_LIST',
    UPDATE_CATEGORY_SCREEN:'UPDATE_CATEGORY_SCREEN',
    UPDATE_HOME_SCREEN:'UPDATE_HOME_SCREEN',
    GOTO_PARTICULAR_CATEGORY_FROM_HOME:'GOTO_PARTICULAR_CATEGORY_FROM_HOME',
    GOTO_PARTICULAR_FRP_CATEGORY_FROM_HOME:'GOTO_PARTICULAR_FRP_CATEGORY_FROM_HOME'
};
export default events;