import {StyleSheet} from 'react-native';
import resources from '../../../res';
import {isPlatformIOS, myWidth, wp} from '../../utility/Utils';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    //backgroundColor: resources.colors.white,
    backgroundColor: '#F7F7F8',
  },
  flex1: {
    flex: 1,
    // marginTop: 10
  },
  loginContainer: {
    marginHorizontal: 20,
  },
  directionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowDirection: {
    flexDirection: 'row',
  },
  cityName: {
    color: resources.colors.labelColor,
    fontWeight: '500',
    fontSize: 14,
    fontFamily: resources.fonts.medium,
  },
  addAddressLnk: {
    color: resources.colors.appBlue,
  },
  columnDirection: {
    flexDirection: 'column',
    marginHorizontal: 5,
  },
  serviceCon: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 110,
    marginTop: 10,
  },
  marginHorizontal: {
    marginHorizontal: 20,
    marginTop: 10,
  },

  viewCard: {
    height: 110,
    width: '100%',
    // flex: 1,
    // justifyContent: 'flex-end',
    // marginHorizontal: 20,
    // paddingVertical: 10,
    marginBottom: 10,
    borderRadius: 6,
    // backgroundColor: resources.colors.white,
    // backgroundColor: 'red',
    flexDirection: 'row',
    // shadowColor: 'rgba(0,0,0,0.8)',
    // shadowOffset: {
    //   width: 1,
    //   height: 0,
    // },
    // shadowRadius: 4,
    // shadowOpacity: 0.3,
    // elevation: 6,
    // borderWidth: 1,
    marginTop: 10,
  },
  summerText: {
    fontFamily: resources.fonts.regular,
    fontSize: 14,
    fontWeight: '600',
    color: resources.colors.timerColor,
    marginHorizontal: 20,
    marginTop: 10,
  },
  frpImageViewCard: {
    flexDirection: 'row',
  },
  frpViewCard: {
    // height: 150,
    // borderWidth: 1,
    marginTop: 5,
    width: '100%',
    // flex: 1,
    marginBottom: 10,
    borderRadius: 6,
    //backgroundColor: resources.colors.white,
    // shadowColor: 'rgba(0,0,0,0.8)',
    // shadowOffset: {
    //   width: 1,
    //   height: 0,
    // },
    // shadowRadius: 2,
    // shadowOpacity: 0.3,
    // elevation: 6,
  },
  cardContainer: {
    flexDirection: 'column',
    marginLeft: 16,
    marginTop: 0,
    flex: 1,
  },
  imageStyle: {
    width: 120,
    height: 120,
    borderRadius: 12,
  },
  frpImageStyle: {
    width: 120,
    height: 120,
    borderRadius: 12,
    marginTop: 10,
  },
  valuesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    // marginBottom: 10,
    justifyContent: 'space-between',
    marginTop: 10,
  },
  titleName: {
    color: resources.colors.labelColor,
    fontSize: 14,
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    // width: "80%"
  },
  applyText: {
    color: 'rgb(28,28,28)',
    fontSize: 18,
    fontFamily: resources.fonts.regular,
    fontWeight: '600',
    marginTop: -10,
  },
  freeServiceText: {
    color: 'rgb(28,28,28)',
    fontSize: 18,
    fontFamily: resources.fonts.regular,
    fontWeight: '600',
    // marginBottom: 10,
    marginTop: 18,
  },
  orderText: {
    color: resources.colors.gray_222222,
    fontSize: 18,
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
  },
  subTitleName: {
    fontFamily: resources.fonts.regular,
    fontSize: 12,
    color: '#71717A',
    marginTop: isPlatformIOS ? 3 : 2,
  },
  subTitleName1: {
    fontFamily: resources.fonts.regular,
    fontSize: 12,
    color: '#000',
    fontWeight: '600',
    marginTop: isPlatformIOS ? 3 : 2,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  crossStyle: {
    height: 17,
    width: 17,
  },
  detailCard1: {
    marginHorizontal: 16,
    marginTop: 25,
    backgroundColor: resources.colors.white,
    padding: 24,
    borderRadius: 12,
  },
  detailCard: {
    marginTop: 24,
  },
  orderValuesText: {
    textAlign: 'right',
    fontFamily: resources.fonts.medium,
    fontSize: 14,
    color: resources.colors.gray_222222,
    fontWeight: '500',
  },
  orderValuesTextGreen: {
    color: resources.colors.uploadedText,
  },
  orderPropText: {
    fontFamily: resources.fonts.medium,
    fontSize: 14,
    color: resources.colors.grayColor,
    fontWeight: '500',
  },
  orderPropTextGreen: {
    fontFamily: resources.fonts.regular,
    fontSize: 12,
    color: resources.colors.uploadedText,
    marginTop: isPlatformIOS ? 12 : 10,
    fontWeight: 'bold',
  },
  orderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  totalContainer: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    paddingHorizontal: 10,
    alignItems: 'center',
    // height: 40,
    marginBottom: 5,
    // flex:1
  },
  orderCardContainer: {
    // marginHorizontal: 10,
    flex: 1,
  },
  totalTextStyle: {
    fontFamily: resources.fonts.bold,
    fontSize: 14,
    color: '#71717A',
    marginTop: 10,
    fontWeight: '500',
  },
  emiTextStyle: {
    fontFamily: resources.fonts.bold,
    fontSize: 12,
    color: resources.colors.appColor,
    marginTop: 4,
    // marginHorizontal: 10
  },
  instructionContainer: {
    marginTop: 6,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  iconTextContainer: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    // marginTop: 20,
    marginBottom: 20,
  },
  kycTextContainer: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  iconStyle: {
    width: 19,
    height: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconTruck: {
    width: 15,
    height: 13,
    marginLeft: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  instructionText: {
    fontFamily: resources.fonts.regular,
    fontSize: 11.5,
    color: 'rgb(28,28,28)',
    marginLeft: 10,
  },
  textInputStyle: {
    flex: 1,
    padding: 0,
    height: 50,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingVertical: 0,
    fontSize: 14,
    color: resources.colors.black,
    fontFamily: resources.fonts.regular,
    //borderBottomWidth: 1,
    //marginRight: 40,
    //borderBottomColor: 'rgba(54,69,79,0.5)',
    top: 0,
    backgroundColor: resources.colors.white,
    borderRadius: 10,
  },
  buttonStyle: {
    width: 92,
    height: 36,
    borderRadius: 6,
  },
  normalButton: {
    width: 92,
    height: 36,
    borderWidth: 1,
    borderColor: 'red',
    borderStyle: 'dashed',
    borderRadius: 6,
    backgroundColor: resources.colors.white,
    padding: 2,
  },
  normalTextStyle: {
    color: 'black',
    fontSize: 12,
    fontFamily: resources.fonts.regular,
  },
  btnTextStyle: {
    // color: '#3a3a3a',
    fontSize: 12,
    fontFamily: resources.fonts.regular,
    // borderWidth:1,
    textAlign: 'center',
  },
  grayBackground: {
    backgroundColor: resources.colors.white,
    flex: 1,
  },
  offerTextButtonCon: {
    flex: 1,
    flexDirection: 'row',
    // marginTop: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginBottom: 5,
    marginVertical: 3,
  },
  offerTextStyle: {
    marginRight: 15,
    fontSize: isPlatformIOS ? 10 : 11,
    fontFamily: resources.fonts.regular,
    color: 'rgb(28,28,28)',
    lineHeight: 15,
  },
  boldTextStyle: {
    marginRight: 3,
    fontSize: 12,
    fontFamily: resources.fonts.bold,
    color: 'rgb(28,28,28)',
  },
  mediumTextStyle: {
    marginRight: 15,
    fontSize: 12,
    fontFamily: resources.fonts.regular,
    color: 'rgb(28,28,28)',
  },
  seprator: {
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(54,69,79,0.5)',
    marginVertical: 5,
  },
  seprator1: {
    marginTop: 10,
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(54,69,79,0.5)',
  },
  serviceIcon: {
    height: 25,
    width: 25,
  },
  space: {
    width: 70,
  },
  rowTextCon: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    flex: 1,
  },
  couponCardCon: {
    // backgroundColor: resources.colors.white,
    borderRadius: 6,
    marginTop: 8,
    // shadowColor: 'rgba(0,0,0,0.3)',
    // shadowOffset: {
    //   width: 0,
    //   height: 0,
    // },
    // shadowRadius: 2,
    // shadowOpacity: 1,
    // elevation: 6,
  },
  textInputCon: {
    flexDirection: 'row',
    marginHorizontal: 0,
    marginTop: 22,
    marginBottom: 12,
  },
  applyBtn: {
    position: 'absolute',
    right: 13,
    justifyContent: 'center',
    top: 15,
  },
  checkotBtnStyle: {
    width: 130,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
    marginBottom: 20,
    backgroundColor: resources.colors.appColor,
    // marginRight: 20,
  },
  chooseDuration: {
    fontSize: 14,
    color: resources.colors.uploadedText,
    fontFamily: resources.fonts.medium,
    fontWeight: '600',
  },
  footerStyle: {
    marginHorizontal: 20,
  },
  cartButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    width: '100%',
    borderTopColor: 'rgba(10,36,99,0.1)',
    alignItems: 'center',
    height: 80,
    backgroundColor: resources.colors.white,
    position: 'absolute',
    bottom: 0,
    zIndex: 9999,
    // paddingHorizontal: 20,
  },
  totalStyle: {
    color: resources.colors.gray_222222,
    fontSize: 20,
    fontFamily: resources.fonts.bold,
    fontWeight: '600',
  },
  appliedText: {
    color: resources.colors.green_2D9469,
    fontSize: wp(12),
    fontFamily: resources.fonts.bold,
  },
  viewMoreText: {
    fontFamily: resources.fonts.bold,
    // fontSize: 12,
    color: resources.colors.bluish,
    textDecorationLine: 'underline',
    textAlign: 'center',
    marginBottom: 5,
  },
  borderClass: {
    borderWidth: StyleSheet.hairlineWidth,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#DDDDDF',
    borderColor: '#DDDDDF',
  },
  coinTxt: {
    marginVertical: 5,
    marginHorizontal: 20,
    color: resources.colors.appOrange,
    fontFamily: resources.fonts.bold,
    fontWeight: '600',
  },
  coinContainer: {
    height: 30,
    borderColor: resources.colors.appOrange,
    borderWidth: 1,
    borderRadius: 28,
  },
  coinContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgCoin: {
    width: 32,
    height: 32,
    left: -13,
    position: 'absolute',
  },
  productContainer: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 25,
    paddingBottom: 25,
  },
  productBorder: {},
  valueTitleText: {
    fontFamily: resources.fonts.regular,
    fontWeight: '400',
    fontSize: 12,
    color: resources.colors.labelColor,
  },
  valueText: {
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    fontSize: 14,
    color: resources.colors.gray_222222,
  },
  cityShieldContainer: {
    backgroundColor: resources.colors.white,
    marginHorizontal: wp(15),
    padding: wp(25),
    borderRadius: wp(12),
    marginVertical: wp(25),
  },
  shieldHeader: {
    marginBottom: wp(20),
  },
  imgShield: {
    height: wp(30),
    width: wp(30),
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shieldHeaderTitle: {
    color: resources.colors.green_2D9469,
    fontFamily: resources.fonts.medium,
    fontWeight: '700',
    fontSize: wp(20),
    fontStyle: 'italic',
  },
  shieldHeaderDetailTxt: {
    fontFamily: resources.fonts.regular,
    color: resources.colors.grayColor,
    fontSize: wp(14),
    marginTop: wp(8),
  },
  borderView: {
    borderWidth: 0.5,
    borderColor: resources.colors.borderDot,
    marginHorizontal: 16,
  },
  shieldContent: {},
  priceView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  offerPrice: {
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    color: resources.colors.headingBlack,
    fontSize: wp(18),
  },
  orinalPrice: {
    fontFamily: resources.fonts.regular,
    fontWeight: '400',
    color: resources.colors.labelColor,
    fontSize: wp(14),
    textDecorationLine: 'line-through',
  },
  txtDiscountPercent: {
    marginLeft: wp(5),
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    color: resources.colors.white,
    fontSize: wp(12),
    textDecorationLine: 'line-through',
  },
  imgPercent: {
    height: wp(18),
    width: wp(18),
  },
  offerView: {
    backgroundColor: resources.colors.uploadedText,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(4),
    height: wp(30),
    paddingHorizontal: wp(10),
    paddingVertical: wp(10),
    borderRadius: wp(5),
  },
  btnRemove: {
    borderRadius: wp(8),
    backgroundColor: resources.colors.white,
    borderWidth: 1,
    borderColor: resources.colors.grayColor,
  },
  btnRemoveTxt: {
    color: resources.colors.grayColor,
    fontSize: wp(14),
    fontFamily: resources.fonts.bold,
    fontWeight: '500',
    marginHorizontal: wp(10),
    marginVertical: wp(5),
  },
  limitedPeriodOffer: {
    width: wp(myWidth * 0.36),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: resources.colors.purple_5B48BF,
    borderRadius: wp(5),
    marginTop: wp(8),
  },
  txtLimitedPeriod: {
    fontFamily: resources.fonts.medium,
    fontSize: wp(10),
    fontWeight: '500',
    color: resources.colors.purple_5B48BF,
    marginLeft: wp(5),
  },
  imgStar: {
    height: wp(15),
    width: wp(15),
  },
  couponContainer: {
    marginTop: wp(20),
  },
  couponContainerTitle: {
    marginHorizontal: wp(16),
    fontFamily: resources.fonts.medium,
    fontSize: wp(18),
    fontWeight: '500',
    color: resources.colors.gray_222222,
  },
  orderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: wp(20),
  },
  imgDotLine: {
    height: 1,
    width: '100%',
    marginBottom: wp(20),
  },
  noEMIContainer: {
    marginHorizontal: wp(16),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: wp(20),
    marginBottom: wp(20),
  },
  imgEMI: {
    width: wp(30),
    height: wp(30),
  },
  txtEMI: {
    marginLeft: wp(10),
    fontFamily: resources.fonts.medium,
    fontSize: wp(14),
    fontWeight: '500',
    color: resources.colors.titleBlack,
    flex: 1
  },
  paymentContianer: {
    backgroundColor: '#3F5093',
    width: myWidth - 35,
    marginLeft: 16,
    paddingVertical: 25,
    borderRadius: 12,
    paddingHorizontal: 20,
    minHeight: 100,
  },
  paymentOfferTitle: {
    fontFamily: resources.fonts.regular,
    fontWeight: '400',
    fontSize: 14,
    color: resources.colors.white,
  },
  paymentOfferSubtitle: {
    fontFamily: resources.fonts.regular,
    fontSize: 12,
    fontWeight: '400',
    color: resources.colors.borderDot,
  },
  paymentOfferTerms: {
    marginTop: 20,
    color: resources.colors.white,
    textDecorationLine: 'underline',
    fontFamily: resources.fonts.regular,
    fontWeight: '500',
  },
  imgEllipseLeft: {
    height: wp(20),
    width: wp(20),
    position: 'absolute',
    left: -wp(6),
    alignSelf: 'center',
    top: wp(50),
  },
  imgEllipseRight: {
    height: wp(20),
    width: wp(20),
    position: 'absolute',
    right: -wp(6),
    alignSelf: 'center',
    top: wp(50),
  },
  thingsContainer: {
    marginHorizontal: wp(16),
    marginVertical: wp(20),
  },
  thingsTitleText: {
    fontSize: wp(18),
    fontWeight: '500',
    color: resources.colors.gray_222222,
    fontFamily: resources.fonts.medium,
  },
  thingsItem: {
    marginTop: wp(25),
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  imgThings: {
    width: wp(30),
    height: wp(30),
  },
  txtThingsItem: {
    flex: 1,
    color: resources.colors.titleBlack,
    fontWeight: '400',
    fontFamily: resources.fonts.regular,
    fontSize: wp(14),
    marginLeft: wp(15),
  },
  freeServiceHeaderTitle: {
    marginHorizontal: wp(16),
    fontSize: wp(18),
    fontWeight: '500',
    fontFamily: resources.fonts.medium,
    color: resources.colors.gray_222222,
    marginTop: wp(20),
  },
  freeServiceItem: {
    backgroundColor: '#222222',
    borderRadius: wp(12),
    padding: wp(16),
    width: wp(myWidth / 2.1 - 32),
    marginLeft: wp(16),
  },
  freeServiceImage: {
    marginTop: wp(10),
    height: wp(32),
    width: wp(32),
  },
  txtFreeServiceTitle: {
    color: resources.colors.white,
    fontSize: wp(16),
    marginTop: wp(10),
    fontWeight: '500',
    fontFamily: resources.fonts.medium,
  },
  txtFreeServiceDetail: {
    color: resources.colors.gray_C0C0C6,
    fontSize: 12,
    marginTop: wp(10),
    fontWeight: '400',
    fontFamily: resources.fonts.regular,
  },
  addressItem: {
    flexDirection: 'row',
    marginHorizontal: wp(16),
    marginBottom: wp(20),
  },
  imgAddressPin: {
    height: wp(30),
    width: wp(30),
  },
  addressItemRightView: {
    marginLeft: wp(12),
    width: wp(myWidth - 74),
  },
  addressItemRightTopView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressItemRightTopViewTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addressItemActionButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtName: {
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    fontSize: wp(16),
    color: resources.colors.grayColor,
  },
  defaultTag: {
    backgroundColor: resources.colors.appBlue,
    paddingHorizontal: wp(8),
    paddingVertical: wp(4),
    color: resources.colors.white,
    borderRadius: wp(8),
    marginLeft: wp(8),
  },
  imgActionButton: {
    width: wp(20),
    height: wp(20),
    marginLeft: wp(12),
  },
  editAddressView: {
    marginTop: wp(12),
  },
  addressItemCenterView: {
    marginTop: wp(12),
  },
  txtAddress1: {
    fontFamily: resources.fonts.regular,
    fontWeight: '400',
    fontSize: wp(14),
    color: resources.colors.grayColor,
  },
  txtAddress2: {
    fontFamily: resources.fonts.medium,
    fontWeight: '600',
    fontSize: wp(14),
    color: resources.colors.grayColor,
    marginTop: wp(8),
  },
  txtEditAddress: {
    textDecorationLine: 'underline',
    fontFamily: resources.fonts.bold,
    fontWeight: '500',
    fontSize: wp(14),
    color: resources.colors.titleBlack,
  },
  btnSubmit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    marginTop: wp(20),
  },
  defaultAddress: {
    flexDirection: 'row',
    marginTop: wp(8),
    alignItems: 'center',
    marginBottom: wp(15),
  },
  defaultAddressimg: {
    height: wp(20),
    width: wp(20),
  },
  defaultText: {
    marginLeft: wp(12),
    fontFamily: resources.fonts.regular,
    fontSize: wp(16),
    color: resources.colors.grayColor,
  },
  btnGreen: {
    borderColor: resources.colors.uploadedText,
  },
  btnGreenText: {
    color: resources.colors.uploadedText,
    marginHorizontal: wp(22),
  },
  txtCityshieldDetail: {
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    fontSize: wp(14),
    color: resources.colors.titleBlack,
  },
  cityshieldItem: {
    marginTop: wp(24),
    flexDirection: 'row',
    alignItems: 'center',
  },
  imgBreakHelp: {
    height: wp(24),
    width: wp(24),
  },
  txtBreakHelp: {
    fontFamily: resources.fonts.regular,
    fontWeight: '500',
    fontSize: wp(14),
    color: resources.colors.titleBlack,
    marginLeft: wp(10),
  },
  btnContinue: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(myWidth - 40),
    paddingHorizontal: 15,
    backgroundColor: resources.colors.appBlue,
    color: resources.colors.appBlue
  },
  lnkButton: {
    backgroundColor: resources.colors.white,
  },
  lnkButtonTxt: {
    color: resources.colors.grayColor,
    fontFamily: resources.fonts.medium,
    fontWeight: '500',
    fontSize: wp(14),
  },
  applyCoupenTextContainer: {
    marginTop: wp(12), flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginHorizontal: wp(16)
  },
  btnClose: {
    height: wp(20), width: wp(20), borderRadius: wp(10), flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'red'
  }
});
export default styles;
