const strings = {
  APP_NAME: 'Cityfurnish',
  NO_INTERNET_CONNECTION: 'No internet Connection',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  NAME: 'Name',
  EMAIL_ADDRESS: 'Email Address',
  EMAIL_OR_MOBILE: 'Email / Mobile Number',
  PASSWORD: 'Password',
  MOBILE_NUMBER: 'Mobile Number',
  REFFERAL: 'Referral Code (optional)',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  DONT_HAVE_ACCOUNT: 'Do not have an account?',
  SIGN_IN_VIA: 'Or Sign in Via',
  FORGOT_PASSWORD: 'Forgot Password?',
  SUBMIT: 'Submit',
  REUPLOAD: 'Re-Upload',
  FORGOT_PASSWORD_INFO_TEXT:
    'Please enter the registered Email address to receive the verification code',
  FEEDBACK_INFO_TEXT:
    'Getting your words about Cityfurnish is great. Rate us on our recent interaction and give your valuable feedback.',
  SORT: 'Sort',
  SELECT_CITY: 'Select City',
  GET_OTP: 'Get OTP',
  SIGN_UP_VIA: 'Or Sign Up Via',
  accountNumberCannotBeEmpty: 'Account Number Field is empty.',
  ifscCodeCannotBeEmpty: 'IFSC Code Field is empty.',
  beneficiaryNameCannotBeEmpty: 'Beneficiary Name Field is empty.',
  nameCannotBeEmpty: 'Name Field is empty.',
  name20length: 'Name should be 20 characters maximum.',
  name2length: 'Name should be 2 characters minimum.',
  phoneCannotBeEmpty: 'Mobile Number Field is empty.',
  alternatePhoneCannotBeEmpty: 'Alternate Mobile Number Field is empty.',
  ownerNameCannotBeEmpty: 'Owner Name Field is empty.',
  phone10length: 'Mobile Number can not be greater than 10 numbers.',
  enterValidPhone: 'Mobile number is not valid.',
  emailCannotBeEmpty: 'Email Field is empty.',
  passwordCannotBeEmpty: 'Password Field is empty.',
  password6length: 'Password must be 6 characters long.',
  password16length: 'Password length should be 16 characters maximum.',
  email100length: 'Email length should be 100 characters maximum.',
  comment1000length: 'Message length should be 1000 characters maximum.',
  commentRequired: 'The Feedback Field is required',
  enterValidEmail: 'Please enter a valid email address.',
  PROFILE_SETTING: 'Profile Setting',
  INVOICES: 'Invoices',
  REFFERAL_CODE: 'Referral Code',
  SAVE: 'Save',
  OLD_PASSWORD: 'Old Password',
  Current_PASSWORD: 'Current Password',
  NEW_PASSWORD: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CHANGE_PASSWORD: 'Change Password',
  MISMATCH_PASSWORD: 'Please enter correct confirm password.',
  VERIFY: 'Verify',
  VERIFIED: '( Verified )',
  NOT_VERIFIED: '(Not Verified)',
  FILTER: 'Filters',
  selectCityText: 'Select your city',
  APPLY: 'Apply',
  OTP: 'Otp',
  VERIFY_OTP: 'Verify',
  otpCannotBeEmpty: 'Otp Field is empty.',
  RESEND_OTP: 'Resend Code',
  otp4length: 'OTP length should be 4 numbers.',
  DIDNT_RECIEVED_CODE: 'Did not receive a verification code',
  OtpSscreenText:
    'A verification code was sent to your registered mobile number.',
  enterOtpText: 'Enter 5 Digit OTP sent you at',
  errorEnterOtp: 'Please fill OTP correctly.',
  verifyYourNumber: 'Please verify your number.',
  FEEDBACK: 'Feedback',
  FORGOT_PASSWORD_TITLE: 'Forgot Password',
  RESET_PASSWORD_TITLE: 'Reset Password',
  EMAIL_INFO_TEXT: 'Email address is required to register with Cityfurnish.',
  Below_TEXT:
    'Below mentioned fields are required to register with Cityfurnish.',
  DASHBOARD: 'Dashboard',
  phoneFieldShouldBeNumber: 'Mobile number should be a number',
  verifyNumberFirst: 'Please verify the number first',
  HAVE_YOUR_FRIEND_TEXT: 'Have your friends pay for your furniture',
  SHARE_YOUR_REFERRAL_CODE:
    'Share your referral code with friends, both you and your friend get',
  YOUR_REFERRAL_CODE: 'Your referral code:',
  SHARE: 'Share',
  COPY: 'COPY',
  KYC_VERIFY_TEXT: 'KYC Documents to be submitted before Delivery',
  CANCELLATION_TEXT: 'Free Cancellation before Delivery',
  ALL_CONDITION_TEXT: 'All Products are in Mint Condition',
  PEOPLE_BOUGHT_TITLE: 'People also bought together',
  RECOMMENDED_PRODUT_TITLE: 'Recommended Product',
  CUSTOMER_SAY_TITLE: "What our Customer's say..",
  CHECK_OFFER_TEXT: 'Check all offer',
  VIEW_ALL_TEXT: 'View All',
  BRAND_TEXT: 'Brand(s)',
  QUANTITY_TEXT: 'Quantity',
  SIZE_TEXT: 'Size',
  MATERIAL_TEXT: 'Material',
  COLOR_TEXT: 'Colour',
  SPECIFICATION_TITLE: 'Specifications',
  CHOOSE_DURATION_TEXT: 'Choose your Duration',
  ADD_TO_CART: 'Add to Cart',
  BUY_NOW: 'Buy Now',
  PleaseEnterEmail: 'Please enter the registered Email address',
  Wishlist: 'Wishlist',
  Filter: 'Filter',
  Sort: 'Sort',
  Address: 'Address',
  FullName: 'Full Name *',
  MobileNumber: 'Mobile Number *',
  alternateMobileNumber: 'Alternate Mobile Number *',
  Addressline1: 'Flat no., building no, etc *',
  EnterAddress: 'Enter Address *',
  Addressline2: 'Street, Colony, Address, etc *',
  EnterSubAddress: 'Flat No, Building No. *',
  City: 'City *',
  CITY: 'City',
  State: 'State *',
  Postalcode: 'Postal code *',
  addAddress: 'Add & Proceed',
  Proceed: 'Proceed',
  addressCannotBeEmpty: 'Flat No, Building No. Field is empty.',
  addressCannotBeEmpty2: 'Street, Colony, Address, etc.',
  AddressNotValid: 'Address not valid',
  cityCannotBeEmpty: 'City Field is empty.',
  cityCannotBeDelivered: 'Selected location is not serviceable at the moment',
  postalCodeCannotBeDelivered:
    'Selected location is not serviceable at the moment',
  cityCurrentLocationCannotBeDelivered:
    'Current location is not serviceable at the moment',
  StateCannotBeEmpty: 'State Field is empty.',
  postalCodeCannotBeEmpty: 'Postal code Field is empty.',
  postalCodeLength: 'Postal code not valid ',
  requrementCanNotBeEmpty: 'Requirement field is empty',
  requrementCanNotBeLessThan30:
    'Requirement should be minimum of 30 characters',
  MAKE_DEFAULT_ADDRESS: ' Make This My Default Address',
  Email: 'Email',
  COPIED_CODE_MSG: 'Referral Code is Copied.',
  Skip: 'Skip',
  NO_DATA_FOUND: 'No Data found',
  NO_ADDRESS_FOUND: 'No Address Added',
  Address5length: 'Address 1 should be atleast 5 characters long.',
  Address5length2: 'Address 2 should be atleast 5 characters long.',
  Flat5length: 'Flat No, Building No. should be atleast 5 characters long.',
  Pay_Now: 'Pay Now',
  Total_OutStanding: 'Total Outstanding -',
  Total_InvoiceDue: 'Amount due for your subscription',
  No_Invoice_Found: 'No Invoice Found',
  No_Transaction_Found: 'No Transactions Found',

  SEARCH: 'Search',
  FIRST_NAME: 'First Name *',
  LAST_NAME: 'Last Name (Optional)',
  EMAIL_REGISTERED: 'Email (registered with cityfurnish)',
  INVOICE: 'Invoice Number (Optional)',
  NOTES: 'Notes (Optional)',
  AMOUNT: 'Amount (Rs.)',
  CF_COIN_REDEEMED: 'Enter Coins to be Redeemed',
  YOUR_CF_COINS: 'Your CF Coins Balance',
  REDEEM: 'Redeem',
  INSTRUCTION:
    'Opt for the standing insrtuctions to avoid hassle of manual payment every month.',
  AutoPay: 'Auto Pay',
  AutoPayDesc:
    'Opt for auto debit via your preferred payment mode and enjoy additional benefits',
  NachDesc:
    'After verifying your account details, you will be redirected to upload form page where you can download the form, sign it and upload it for successful paper NACH.',
  CHECK_TOTAL_OUTSTANDING: 'Your Outstanding Amount',
  Check_Details: 'Check Details',
  EDIT_ADDRESS: 'Edit Address',
  MANAGE_ORDER: 'Manage Orders',
  DESCRIPTION: 'Description',
  ATTACHMENT: 'Attachment',
  CURRENT_PAYMENT_MODE: 'Current Payment Mode',
  CHANGE_PAYMENT_MODE: 'Change Payment Mode',
  NEW_PAYMENT_MODE: 'New Payment Mode',
  CART: 'Cart',
  CITYMAX: 'CITYMAX',
  MY_ACCOUNT: 'My Account',
  searchHint: 'Search...',
  PROCEED: 'Proceed',
  TOTAL: 'Total',
  REMOVE: 'Remove',
  ORDER_DETAIL: 'Order Detail',
  FREE_SERVICES: 'Your Free Services *',
  APPLY_CODE: 'Apply Coupon',
  APPLY_CODE1: 'Offers and benefits',
  FREE_DELIVERY: 'Free Delivery',
  FREE_RELOCATION: 'Free Relocation',
  FREE_UPGRADE: 'Free Upgrade',
  FREE_INSTALLATION: 'Free Installation',
  MINT_CONDITION: 'Mint Condition',
  DAMAGE_WAIVER: 'Damage Waiver',
  ADD_PRODUCT_MSG: 'Please add some products on Cart',
  NO_PRODUCT_FOUND: 'Your Cart is Empty',
  youNeedLogin: 'You need to login to access this feature.',
  mobileVerified: 'Verified',
  cityfunishCoins: 'Cityfurnish Coins',
  enterAmount: 'Enter the amount',
  amountCannotBeEmpty: 'Amount Field is empty.',
  OFFICE_ENQUIRY: 'Office Furniture Enquiry',
  ENTER_FULL_NAME: "What's your name? *",
  ENTER_MOBILE_NO: 'Enter Mobile number *',
  ENTER_EMAIL: 'Enter Email *',
  ENTER_DEALCODE_NUMBER: 'Enter Order Id (if any) *',
  ENTER_CITY: 'Your City *',
  ENTER_REQUREMENT: 'Your Requirement *',
  Customer_Payment: 'Customer Payment',
  Corporate_Orders: 'Corporate Orders',
  corporateDiscription:
    'If your home or business requirement calls for a bulk order, Cityfurnish offers turnkey services that cater to all needs: from setting up a new home, to furniture for your office or business venture.',
  MESSAGE: 'Message',
  EMPTYMESSAGE: 'Message cannot be empty.',
  CUSTOMMADEPRODUCT: 'Custom Made Products',
  CUSTOMPRODUCTDISCRIPTION:
    'Need something unique? We will make it for you. We provide custom made furniture as per the demand of your project',
  CALL: 'Call:',
  HELPLINENO: '080-66084700',
  OURPROJECT: 'Our Projects',
  CONTACT_US: 'Contact Us',
  CAN_NOT_FIND_ANSWER: 'Still can not find an answer?',
  FILL_FREE_CONTACT_US:
    'Feel free to contact us with service questions, business proposals or media inquiries.',
  BENEFITS: 'Benefits',
  FULL_FILL_CORPORATE_NEED: 'Fulfilling all your corporate needs',
  ENQUIRY_REQUREMENT:
    'Mention your requirements in brief & we will get back to you promptly',
  ENQUIRY: 'Enquire',
  NOTIFICATION: 'Notifications',
  NOTIFICATION_TITLE: 'Welcome to Cityfurnish',
  NOTIFICATION_SUB_TITLE:
    "Let's see your activity, update, and order notifications",
  VIEW_ALL: 'VIEW ALL',
  OFFERS: 'Offers',
  UPFRONT: 'UpFront Plans',
  OFFER_JUST_FOR_YOU: 'Offers just for you!',
  COUPON_CODE: 'Coupon code',
  COUPON_CODE_COPYIED: 'Coupon code Copied',
  MONTHLY_RENT: 'Monthly Rent',
  ITEM_INCLUDE: 'Item(s) included',
  ADD_COIN: 'Add Coin',
  CHOOSE: 'Choose',
  INVOICE_NUMBER: 'Invoice Number',
  TRANSACTION_ID: 'Transaction ID',
  MY_PAYMENT: 'My Payments',
  DOWNLOAD_STATEMENT: 'Download Statement',
  conis1length: 'You can not add coins less than 1.',
  CREDIT_CARD: 'Credit Card',
  DEBIT_CARD: 'Debit Card',
  OTHER: 'Other',
  YOUR_COINS_BALANCE: 'Your Coin Balance',
  CURRENT_BALANCE: 'Current Balance',
  TOTAL_COIN_WORTH: 'Your Total coins are worth',
  REDEEM_DESCRIPTION:
    'Coins can be redeemed while making invoice payment or while placing order',
  INSTANCE_CHECKOUT: 'Instant Checkout',
  ONE_CLICK: 'One-click,easy and fast checkout',
  MORE_BENEFITS: 'Much More Benefits',
  USING_CF_COINS: 'Benefits and offers on uisng CF Coins',
  VIEW_ORDER: 'View Order',
  ORDER_SUMMERY: 'Order Summary',
  SHOPPING_DETAILS: 'Shipping Details',
  MY_ORDER: 'My Orders',
  AUTO_PAY: 'Auto Pay',
  CHOOSE_PRODUCT: 'Choose Product',
  SERVICES_REQUEST_TYPE: 'Service Request Type',
  ORDER_ID: 'Select Your Order',
  HOW_IT_WORKS: 'How IT Works',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  ADD: 'Add',
  OUT_OF_STOCK: 'Out Of Stock',
  addedToWishList: 'Added to wishlist',
  BECOME_BRAND:
    'Become our brand ambassador and earn CF Coins everytime you refer someone',
  Follow_steps:
    'Following is the process of placing order on Cityfurnish. Alternatively you can also call our customer care to place an order.',
  ALL_YOU_KNOW: 'All You Want to Know About It..',
  QUES_AND_ANS: 'Questions and Answers',
  Terms_and_Conditions: 'Terms and Conditions',
  SHARE_REFERAL_CODE:
    'Share your referral code with friends, both you and your friend get',
  REFER_AND_GET_CODE: 'Register and get your Referral Code.',
  KNOW_MORE: 'Know More...',
  REGISTERED: 'Register',
  NEXT: 'Next',
  CHECK_CREDIT_SCORE: 'Check Credit Score',
  VOTER_ID: 'Voter ID',
  DRIVING_LIC: 'Driving Licence',
  PAN_NUMBER: 'Pan Number',
  DOB: 'Date of Birth *',
  voterCannotBeEmpty: 'Voter ID Field is empty.',
  drivingCannotBeEmpty: 'Driving Licence Field is empty.',
  panCannotBeEmpty: 'Pan Number Field is empty.',
  dobCannotBeEmpty: 'DOB Field is empty.',
  Documentation: 'Documentation',
  Select_Order: 'Select Order',
  KycInstruction:
    'We require some documents before delivery. Documents submitted are used solely for the purpose of identity, address and order verification.',
  KycReUploadInstruction:
    'We require to re-upload some documents before delivery as per request. Please re-upload documents using below form.',
  USER_TYPE: 'User Type *',
  Note: 'Note :',
  KYC_NOTE_LINKEDIN:
    "1. Your Linkedin profile helps our credit rating team to complete KYC faster. Don't worry, we will never post anything on your social profiles.",
  KYC_RATING:
    '2. Based on your credit rating and order value, we might request you to provide some more documents.',
  KYC_ORDER_FULFILLMENT:
    '3. Order fulfillment is subject to approval of documents submitted. Cityfurnish reserves right to cancel order in case of documents rejection.',
  LINKEDIN_PROFILE_URL: 'Linkedin Profile URL',
  SPECIAL_REMARK: 'Special Remarks',
  CHOOSE_FILE: 'Choose File',
  MAX10MB: '( Max 10MB )',
  MAX10MB4FILES: "( Max 10MB And Can't More then 4 Files )",
  TOTAL_QUANTITY: 'Total Quantity (Units)',
  USER_TYPE_EMPTY: 'User Type field is Empty',
  DOCUMENT_TYPE_EMPTY: 'Please select document Type options',
  SPECIAL_REMARK_EMPTY: 'Special remark field is empty',
  NOTIFY_ME: 'Notify Me',
  CorporateName2length: 'Name should be of atleast 2 characters long',
  CorporateCity2length: 'City should be of atleast 2 characters long',
  CorporateMessage5length: 'Message should be of atleast 5 characters long.',
  TotalQuantityEmpty: 'Total Quantity is empty',
  CREDIT_SCORE: 'Credit Score',
  VERIFY_CREDIT_SCORE: 'Verify Credit Score',
  KYC: 'KYC',
  KYC_DOCUMENTS: 'KYC Documents',
  EDIT_KYC_DOCUMENTS: 'Edit KYC Documents',
  AUTO_PAYMENT: 'Setup Auto Pay',
  removedFromWishList: 'Removed from wishlist',
  APPROVED: 'Approved',
  PENDING: 'Pending',
  ORDER_NO: 'Order No',
  ORDER_DATE: 'Order Date',
  KYC_IN_PROGRESS: 'Kyc In Progress',
  CREDIT_SCORE_STATE: 'Credit Score Check Pending',
  KYC_STATE: 'Documents Pending',
  AUTO_PAYMENT_STATE: 'Autopay Registration Pending',
  KYC_DOCS_UNDER_REVIEW_STATE: 'KYC Docs Under Review',
  KYC_COMPLETE: 'Kyc Complete',
  DELIVERY_SECHUDULE: 'Delivery Scheduled',
  DELIVERED: 'Delivered',
  CREDIT_POLICY:
    "By continuing, you agree to allow Cityfurnish India Private Limited to fetch your credit report from CRIF High Mark for the purpose of renting. This consent shall be valid for a period of 3 months. By clicking the 'Proceed' button, you agree to CRIF High Mark Credit Score Terms of Use. You understand that you shall have the option to opt out/unsubscribe from the service by clicking here. Fetching report from the credit bureau will not impact your credit score",
  PLEASE_ADD_ONE_ID: 'Please fill atlast one field',
  pancard10Digit: 'Pan card must be 10 digit',
  enterValidPan: 'Pan number is not valid.',
  PLEASE_SELECT_DATE: 'Please select date of birth',
  REFER_AND_EARN: 'Refer and Earn',
  TOTAL_RENT: 'Total Rent',
  ENQUIRY_NOW: 'Enquire Now',
  ORDER_SUMMARY: 'Order Summary',
  paymentInstruction1:
    '- Your Rental Payment will begin from the date of Delivery.',
  paymentInstruction2:
    '- Once the order has been placed, you might be required to share few documents for KYC.',
  paymentInstruction3: '  share few documents for KYC. ',
  GST_DETAILS: 'GST Details',
  I_HAVE_GST: 'I have GST Number',
  OPT_FOR_WHATSAPP: 'Opt for whatsapp notification',
  GST_NUMBER: 'GST Number',
  COMPANY_NAME: 'Company Name',
  PAYMENT_METHOD: 'Payment Method',
  CREDIT_DEBIT: 'Credit/Debit Card',
  ChoosePaymentMethod: 'Choose your preferred payment method',
  NET_BANKING: 'Net Banking',
  UPI: 'UPI',
  OPT_FOR_STANDING_INSTRUCTION: 'Opt for Standing Instruction',
  SI_Instruction1: '- Get 100 CF coins and gift vouchers worth ₹2500.',
  SI_Instruction2: '- No hassle of reminders and payment delays.',
  SI_Instruction3: '- Supported on selected card issuers/banks',
  SI_Instruction4:
    '- Actual rental amount is deducted at monthly invoice generation only and not during auto pay registration',
  MAKE_PAYMENT: 'Make Payment',
  FaQ: "FAQ's",
  PRODUCT_IMAGES: 'Product Images',
  FIXED_RENTAL_PLAN: 'Fixed Rental Plan',
  OUT_STANDING_PAYMENT: 'Outstanding Payment',
  Owner_Mobile: "Owner's mobile number",
  Alternate_Customer_Mobile: "Alternate Customer's mobile number",
  Owner_Name: "Owner's name",
  User_Details: 'User Details',
  BENEFITS_RENTAl: 'Benefits with Rental',
  BENEFITS_DESC:
    'Following are the benefits of placing an order with Cityfurnish. Because Renting from cityfurnish is great',
  SAFETY_RENTAl: '#StaySafe',
  SAFETY_DESC:
    "By following WHO guidelines, we ensure your order's safety at every step.",
  // No_Transaction_Found: 'No Transaction Found',
  razorpayTitle: 'Cityfurnish',
  razorpayDescription: 'Customer payment mode',
  razorpayPayOutStandingDescription: 'PayOut Standing payment mode',
  eazyRazorpayPaymentDescription: 'Eazy payment mode',
  razorpayOrderDescription: 'Order payment mode',
  razorpayCurrency: 'INR',
  razorpayImageUrl:
    'https://d3juy0zp6vqec8.cloudfront.net/images/brand-logo.png',
  clientId: '9xp1li04',
  clientSecret: 'p0qej1xa12gr5d6o',
  understood: 'Understood',
  upload_file: 'Upload file',
  go_home: 'Go Home',
  how_can_i_help_you: 'How can we help you?',
  order_id: 'Order Id',
  need_help: 'Need help with..',
  create_request: 'Create request',
  proceed_to_pay: "Proceed to Pay",
  save_address: "Save address",
  Beforeweproceed:"Before we proceed"
};
export default strings;
