// export const BASE_URL = "http://45.113.122.221"; // Development
export const BASE_URL = 'https://rentofurniture.com'; // Stagging
//export const BASE_URL = 'https://cityfurnish.com'; // Production

/**
 * Api Identifiers
 * example
 * export const LOGIN = 'LOGIN'
 */
export const SIGNUP_API = 'SIGNUP_API';
export const LOGIN_API = 'LOGIN_API';
export const SEND_OTP_API = 'SEND_OTP_API';
export const VERIFY_OTP_AND_LOGIN_API = 'VERIFY_OTP_AND_LOGIN_API';
export const SOCIAL_LOGIN_API = 'SOCIAL_LOGIN_API';
export const VERIFY_OTP_ONLY_API = 'VERIFY_OTP_ONLY_API';
export const UPDATE_PROFILE_API = 'UPDATE_PROFILE_API';
export const CHANGE_PASSWORD_API = 'CHANGE_PASSWORD_API';
export const GET_USER_PROFILE_API = 'GET_USER_PROFILE_API';
export const VERIFY_MOBILE_NUMBER_API = 'VERIFY_MOBILE_NUMBER_API';
export const VERIFY_EMAIL_API = 'VERIFY_EMAIL_API';
export const GET_ALL_CITIES_API = 'GET_ALL_CITIES_API';
export const LINKEDIN_USER_API = 'LINKEDIN_USER_API';
export const DIRECT_SOCIAL_LOGIN_API = 'DIRECT_SOCIAL_LOGIN_API';
export const ALL_PRODUCT_DETAIL_API = 'ALL_PRODUCT_DETAIL_API';
export const GET_OFFERS_API = 'GET_OFFERS_API';
export const CATEGORY_LISTING_API = 'CATEGORY_LISTING_API';
export const ADD_ADDRESS_API = 'ADD_ADDRESS_API';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADDRESS_LISTING_API = 'ADDRESS_LISTING_API';
export const REVIEW_LISTING_API = 'REVIEW_LISTING_API';
export const GET_ALL_WISHLIST = 'GET_ALL_WISHLIST';
export const GET_PRODUCT_LISTING_API = 'GET_PRODUCT_LISTING_API';
export const ADD_DELETE_WISHLIST_API = 'ADD_DELETE_WISHLIST_API';
export const GET_FILTER_LISTING_API = 'GET_FILTER_LISTING_API';
export const DELETE_ADDRESS_API = 'DELETE_ADDRESS_API';
export const GET_STATE_CITY_API = 'GET_STATE_CITY_API';
export const GET_INVOICES_API = 'GET_INVOICES_API';
export const ADD_TO_CART_API = 'ADD_TO_CART_API';
export const GET_CART_DETAIL_API = 'GET_CART_DETAIL_API';
export const SEARCH_PRODUCT_API = 'SEARCH_PRODUCT_API';
export const GET_REFERRAL_CODE_API = 'GET_REFERRAL_CODE_API';
export const DELETE_FROM_CART_API = 'DELETE_FROM_CART_API';
export const DELETE_COUPON_CODE_API = 'DELETE_COUPON_CODE_API';
export const APPLY_COUPON_CODE_API = 'APPLY_COUPON_CODE_API';
export const CORPORATE_ORDER_API = 'CORPORATE_ORDER_API';
export const CORPORATE_ORDER_DETAILS_API = 'CORPORATE_ORDER_DETAILS_API';
export const DEFAULT_ADDRESS_API = 'DEFAULT_ADDRESS_API';
export const GET_FRP_PLANS_API = 'GET_FRP_PLANS_API';
export const GET_CBIL_DOCUMENTS_API = 'GET_CBIL_DOCUMENTS_API';
export const GET_ALL_ORDER_API = 'GET_ALL_ORDER_API';
export const GET_FIRST_RUNNING_ORDER_API = 'GET_FIRST_RUNNING_ORDER_API';
export const GET_ALL_SCHEDULED_ORDER_API = 'GET_ALL_SCHEDULED_ORDER_API';
export const VERIFY_CREDIT_SCORE_API = 'VERIFY_CREDIT_SCORE_API';
export const GET_KYC_SCORE_API = 'GET_KYC_SCORE_API';
export const SAVE_KYC_DATA_API = 'SAVE_KYC_DATA_API';
export const UPLOAD_KYC_DATA_API = 'UPLOAD_KYC_DATA_API';
export const NOTIFY_PRODCUT_API = 'NOTIFY_PRODCUT_API';
export const GET_FRP_PLAN_DETAIL_API = 'GET_FRP_PLAN_DETAIL_API';
export const GET_FRP_SUGGESTION_PRODUCTS_API =
  'GET_FRP_SUGGESTION_PRODUCTS_API';
export const ADD_FRP_PRODUCT_TO_CART_API = 'ADD_FRP_PRODUCT_TO_CART_API';
export const GENERATE_HASH_API = 'GENERATE_HASH_API';
export const GET_CMS_PAGE_DETAIL_API = 'GET_CMS_PAGE_DETAIL_API';
export const GET_VIEW_ORDER_DETAIL_API = 'GET_VIEW_ORDER_DETAIL_API';
export const CART_CHECKOUT_API = 'CART_CHECKOUT_API';
export const CART_CHECKOUT_INITATION_API = 'CART_CHECKOUT_INITATION_API';
export const CART_CHECKOUT_RAZORPAY_API = 'CART_CHECKOUT_RAZORPAY_API';
export const CART_CHECKOUT_RAZORPAY_API_EMANDATE_RECURRING =
  'CART_CHECKOUT_RAZORPAY_API_EMANDATE_RECURRING';
export const CART_CHECKOUT_RAZORPAY_API_CARD_RECURRING =
  'CART_CHECKOUT_RAZORPAY_API_CARD_RECURRING';
export const CART_CHECKOUT_RAZORPAY_API_UPI_RECURRING =
  'CART_CHECKOUT_RAZORPAY_API_UPI_RECURRING';
export const CART_CHECKOUT_RAZORPAY_SUCCESS_API =
  'CART_CHECKOUT_RAZORPAY_SUCCESS_API';
export const CART_CHECKOUT_RAZORPAY_SUCCESS_API_EMANDATE_RECURRING =
  'CART_CHECKOUT_RAZORPAY_SUCCESS_API_EMANDATE_RECURRING';
export const CART_CHECKOUT_RAZORPAY_SUCCESS_API_CARD_RECURRING =
  'CART_CHECKOUT_RAZORPAY_SUCCESS_API_CARD_RECURRING';
export const CART_CHECKOUT_RAZORPAY_SUCCESS_API_UPI_RECURRING =
  'CART_CHECKOUT_RAZORPAY_SUCCESS_API_UPI_RECURRING';
export const GET_PAYMENT_INFO_API = 'GET_PAYMENT_INFO_API';
export const GET_MY_PAYMENT_API = 'GET_MY_PAYMENT_API';
export const GET_CF_COINS_DETAIL_API = 'GET_CF_COINS_DETAIL_API';
export const GET_MANAGE_SERVICE_REQUET_API = 'GET_MANAGE_SERVICE_REQUET_API';
export const GET_MANAGE_SERVICE_REQUEST_POST_API =
  'GET_MANAGE_SERVICE_REQUEST_POST_API';
export const DOWNLOAD_PAYMENT_STATEMENT_API = 'DOWNLOAD_PAYMENT_STATEMENT_API';
export const ENQUIRE_OFFICE_FURNITURE_API = 'ENQUIRE_OFFICE_FURNITURE_API';
export const CHATBOT_QUERY_REQUEST_API = 'CHATBOT_QUERY_REQUEST_API';
export const GET_FAQ_PAGE_DETAIL_API = 'GET_FAQ_PAGE_DETAIL_API';
export const SEND_SERVICE_REQUEST_API = 'SEND_SERVICE_REQUEST_API';
export const REDEEM_COINS_API = 'REDEEM_COINS_API';
export const WALLET_TOPUP_API = 'WALLET_TOPUP_API';
export const INVOICE_PAYMENT_API = 'INVOICE_PAYMENT_API';
export const INVOICE_REMOVE_COINS_API = 'INVOICE_REMOVE_COINS_API';
export const INVOICE_REDEEM_COINS_API = 'INVOICE_REDEEM_COINS_API';
export const CUSTOMER_PAYMENT_API = 'CUSTOMER_PAYMENT_API';
export const CUSTOMER_RAZORPAY_PAYMENT_API = 'CUSTOMER_RAZORPAY_PAYMENT_API';
export const CREATE_CUSTOMER_RAZORPAY_PAYMENT_API =
  'CREATE_CUSTOMER_RAZORPAY_PAYMENT_API';
export const CUSTOMER_RAZORPAY_PAYMENT_SUCCESS_API =
  'CUSTOMER_RAZORPAY_PAYMENT_SUCCESS_API';
export const CREATE_OUTSTANDING_RAZORPAY_PAYMENT_API =
  'CREATE_OUTSTANDING_RAZORPAY_PAYMENT_API';
export const OUTSTANDING_RAZORPAY_PAYMENT_SUCCESS_API =
  'OUTSTANDING_RAZORPAY_PAYMENT_SUCCESS_API';
export const CUSTOMER_RAZORPAY_PAYMENT_API_RECURRING =
  'CUSTOMER_RAZORPAY_PAYMENT_API_RECURRING';
export const CUSTOMER_RAZORPAY_PAYMENT_API_EMANDATE_RECURRING =
  'CUSTOMER_RAZORPAY_PAYMENT_API_EMANDATE_RECURRING';
export const CUSTOMER_RAZORPAY_PAYMENT_API_CARD_RECURRING =
  'CUSTOMER_RAZORPAY_PAYMENT_API_CARD_RECURRING';
export const CUSTOMER_RAZORPAY_PAYMENT_API_UPI_RECURRING =
  'CUSTOMER_RAZORPAY_PAYMENT_API_UPI_RECURRING';
export const EAZY_PAYMENT_API_EMANDATE_RECURRING =
  'EAZY_PAYMENT_API_EMANDATE_RECURRING';
export const EAZY_PAYMENT_API_UPI_RECURRING = 'EAZY_PAYMENT_API_UPI_RECURRING';
export const EAZY_PAYMENT_API_RECURRING = 'EAZY_PAYMENT_API_RECURRING';
export const EAZY_PAYMENT_SUCCESS_API = 'EAZY_PAYMENT_SUCCESS_API';
export const EAZY_PAYMENT_NACH_SUCCESS_API = 'EAZY_PAYMENT_NACH_SUCCESS_API';
export const CUSTOMER_PAYMENT_REDEEM_COINS_API =
  'CUSTOMER_PAYMENT_REDEEM_COINS_API';
export const CUSTOMER_PAYMENT_REMOVE_COINS_API =
  'CUSTOMER_PAYMENT_REMOVE_COINS_API';
export const HOME_SCREEN_API = 'HOME_SCREEN_API';
export const TRENDING_PRODUCT_API = 'TRENDING_PRODUCT_API';
export const GET_CHANGE_TYPE_PAYMENT_MODES_API =
  'GET_CHANGE_TYPE_PAYMENT_MODES_API';
export const CHANGE_PAYMENT_MODE_API = 'CHANGE_PAYMENT_MODE_API';
export const FACEBOOK_USER_API = 'FACEBOOK_USER_API';
export const UPDATE_FCM_DEVICE_TOKEN_API = 'UPDATE_FCM_DEVICE_TOKEN_API';
export const ADD_CF_COIN_API = 'ADD_CF_COIN_API';
export const USER_SERVICE_REQUEST_API = 'USER_SERVICE_REQUEST_API';
export const HOW_IT_WORK_QA_API = 'HOW_IT_WORK_QA_API';
export const GET_APPLE_LOGIN_RESPONSE_API = 'GET_APPLE_LOGIN_RESPONSE_API';
export const GET_UPDATE_WALLET_AMOUNT_API = 'GET_UPDATE_WALLET_AMOUNT_API';
export const VERIFY_CRIF_ANSWER_API = 'VERIFY_CRIF_ANSWER_API';
export const GET_APP_LIVE_VERSION_API = 'GET_APP_LIVE_VERSION_API';
export const GET_CUSTOMER_PAYMENT_URL = 'GET_CUSTOMER_PAYMENT_URL';
export const VALIDATE_CART_API = 'VALIDATE_CART_API';
export const FEEDBACK_API = 'FEEDBACK_API';
export const FEEDBACK_URL_API = 'FEEDBACK_URL_API';
export const USER_NOTIFICATION_API = 'USER_NOTIFICATION_API';
export const UPDATE_CONTACT_API = 'UPDATE_CONTACT_API';
export const GET_NON_SERVICEABLE_POSTALCODE_API =
  'GET_NON_SERVICEABLE_POSTALCODE_API';
export const FRP_FAQ_API = 'FRP_FAQ_API';
export const FRP_HOW_ITS_WORKS_API = 'FRP_HOW_ITS_WORKS_API';
export const FRP_FURNISHING_PLAN_API = 'FRP_FURNISHING_PLAN_API';

/**
 * Endpoints
 * example
 * LOGIN_ENDPOINT = "user/login";
 */
const SIGNUP_ENDPOINT = '/v1/user/signup';
const LOGIN_ENDPOINT = '/v1/user/login';
const SEND_OTP_ENDPOINT = '/v1/user/sendotp';
const VERIFY_OTP_AND_LOGIN_ENDPOINT = '/v1/user/verifyotp';
const SOCIAL_LOGIN_ENDPOINT = '/v1/user/sociallogin';
const VERIFY_OTP_ONLY_ENDPOINT = '/v1/user/onlyotpverify';
const UPDATE_PROFILE_ENDPOINT = '/v1/user/updateprofile';
const CHANGE_PASSWORD_ENDPOINT = '/v1/user/forgotpassword';
const GET_USER_PROFILE_ENDPOINT = '/v1/user/getprofile';
const VERIFY_MOBILE_NUMBER_ENDPOINT = '/v1/user/verifymobile';
const VERIFY_EMAIL_ENDPOINT = '/v1/user/verifyemail';
const ALL_CITIES_ENDPOINT = '/v1/category/getallcities';
const LINKEDIN_USER_ENDPOINT = 'https://api.linkedin.com/v2/me';
const DIRECT_SOCIAL_LOGIN_ENDPOINT = '/v1/user/onlysoiallogin';
const GET_ALL_PRODUCT_DETAIL_ENDPOINT = '/v1/product/getproductdetails';
const GET_OFFERS_ENDPOINT = '/v1/cart/getoffers';
const CATEGORY_LISTING_ENDPOINTS = '/v1/category/getallcategory';
const ADD_ADDRESS_ENDPOINTS = '/v1/cart/addupdateshippingaddress';
const ADDRESS_LISTING_ENDPOINTS = '/v1/cart/shippingaddresslisting';
const REVIEW_LISTING_ENDPOINTS = '/v1/user/getcustomerreview';
const GET_ALL_WISHLIST_ENDPOINTS = '/v1/user/getwishlist';
const GET_PRODUCT_LISTING_API_ENDPOINTS = '/v1/product/getallproducts';
const ADD_DELETE_WISHLIST_API_ENDPOINTS = '/v1/user/addremovefromwishlist';
const GET_FILTER_LISTING_ENDPOINTS = '/v1/filter/getfilters';
const DELETE_ADDRESS_ENDPOINTS = '/v1/cart/deleteshippingaddress';
const GET_STATE_CITY_ENDPOINT = '/v1/cart/getshipstate';
const GET_INVOICES_ENDPOINTS = '/v1/user/getinvoice';
const ADD_TO_CART_ENDPOINTS = '/v1/cart/addtocart';
const GET_CART_DETAIL_ENDPOINTS = '/v1/cart/getcartdetails';
const SEARCH_PRODUCT_ENDPOINTS = '/v1/product/serachproduct';
const GET_REFERRAL_CODE_ENDPOINT = '/v1/user/getreferralcode';
const DELETE_FROM_CART_ENDPOINT = '/v1/cart/removefromcart';
const APPLY_COUPON_CODE_ENDPOINT = '/v1/cart/applycoupon';
const DELETE_COUPON_CODE_ENDPOINT = '/v1/cart/removecoupon';
const CORPORATE_ORDER_ENDPOINT = '/v1/order/savebulkorder';
const CORPORATE_ORDER_DETAILS_ENDPOINTS = '/v1/common/getcorporatedetails';
const DEFAULT_ADDRESS_ENDPOINTS = '/v1/cart/markaddressdefault';
const GET_FRP_PLANS_ENDPOINTS = '/v1/category/getfrp';
const GET_CBIL_DOCUMENTS_ENDPOINTS = '/v1/user/getcibildocuments';
const GET_ALL_ORDER_ENDPOINTS = '/v1/user/getallorders';
const VERIFY_CREDIT_SCORE_ENDPOINTS = '/v1/user/verifycreditscore';
const GET_KYC_SCORE_ENDPOINTS = '/v1/user/getkycscore';
const SAVE_KYC_DATA_ENDPOINTS = '/v1/user/savekycdocs';
const UPLOAD_KYC_DATA_ENDPOINTS = '/site/user_settings/reupload_doc_app';
const NOTIFY_PRODCUT_ENDPOINT = '/v1/product/notifyme';
const GET_FRP_PLAN_DETAIL_ENDPOINT = '/v1/category/getfrpplandetails';
const GET_FRP_SUGGESTION_PRODUCTS_ENDPOINT =
  '/v1/category/getfrpproductdetails';
const ADD_FRP_PRODUCT_TO_CART_ENDPOINT = '/v1/cart/addfrptocart';
const GENERATE_HASH_ENDPOINT = '/v1/common/generatehash';
const GET_CMS_PAGE_DETAIL_ENDPOINT = '/v1/common/getcms';
const GET_VIEW_ORDER_DETAIL_ENDPOINT = '/v1/user/vieworder';
const CART_CHECKOUT_ENDPOINT = '/v1/cart/cartcheckout';
const CART_CHECKOUT_INITATION_ENDPOINT = '/ajxapi/cartcheckout';
const CART_CHECKOUT_RAZORPAY_ENDPOINT = '/ajxapi/create_order';
const CART_CHECKOUT_RAZORPAY_EMANDATE_RECURRING_ENDPOINT =
  '/ajxapi/create_order/emandate';
const CART_CHECKOUT_RAZORPAY_CARD_RECURRING_ENDPOINT =
  '/ajxapi/create_order/card';
const CART_CHECKOUT_RAZORPAY_UPI_RECURRING_ENDPOINT =
  '/ajxapi/create_order/upi';
const CART_CHECKOUT_RAZORPAY_SUCCESS_ENDPOINT = '/ajxapi/save_payment';
const CART_CHECKOUT_RAZORPAY_SUCCESS_EMANDATE_RECURRING_ENDPOINT =
  '/ajxapi/save_payment/emandate';
const CART_CHECKOUT_RAZORPAY_SUCCESS_CARD_RECURRING_ENDPOINT =
  '/ajxapi/save_payment/card';
const CART_CHECKOUT_RAZORPAY_SUCCESS_UPI_RECURRING_ENDPOINT =
  '/ajxapi/save_payment/upi';
const GET_PAYMENT_INFO_ENDPOINT = '/ajxapi/enabled_paymentgateway';
const GET_ALL_SCHEDULED_ORDER_ENDPOINTS = '/ajxapi/easypayments_status';
const GET_MY_PAYMENT_ENDPOINTS = '/v1/user/getmypayments';
const GET_CF_COINS_DETAIL_ENDPOINTS = '/v1/user/getmywallet';
const GET_MANAGE_SERVICE_REQUET_ENDPOINTS = '/v1/user/manageservicerequest';
const GET_MANAGE_SERVICE_REQUEST_POST_ENDPOINTS =
  '/v1/user/manageservicerequest';
const DOWNLOAD_PAYMENT_STATEMENT_ENDPOINTS = '/v1/user/exportpayment';
const ENQUIRE_OFFICE_FURNITURE_ENDPOINTS = '/v1/product/saveenquire';
const GET_FAQ_PAGE_DETAIL_ENDPOINT = '/v1/common/faq';
const SEND_SERVICE_REQUEST_ENDPOINT = '/v1/user/saveservicerequest';
const REDEEM_COINS_ENDPOINT = '/v1/user/applywallet';
const WALLET_TOPUP_ENDPOINT = '/v1/user/wallettopup';
const INVOICE_PAYMENT_ENDPOINT = '/v1/user/invoicepayment';
const INVOICE_REMOVE_COINS_ENDPOINT = '/v1/user/removecoins';
const INVOICE_REDEEM_COINS_ENDPOINT = '/v1/user/redeemcoins';
const CUSTOMER_PAYMENT_ENDPOINT = '/v1/user/customerpayment';
const CUSTOMER_RAZORPAY_PAYMENT_ENDPOINT = '/ajxapi/CustomerPayment';
const CREATE_CUSTOMER_RAZORPAY_PAYMENT_ENDPOINT = '/ajxapi/create_cp_order/';
const CUSTOMER_RAZORPAY_PAYMENT_SUCCESS_ENDPOINT = '/ajxapi/response';
const CREATE_OUTSTANDING_RAZORPAY_PAYMENT_ENDPOINT = '/ajxapi/create_cp_order/';
const OUTSTANDING_RAZORPAY_PAYMENT_SUCCESS_ENDPOINT = '/ajxapi/response';
const CUSTOMER_RAZORPAY_PAYMENT_RECURRING_ENDPOINT =
  '/ajxapi/create_cp_order/emandate';
const CUSTOMER_RAZORPAY_PAYMENT_API_EMANDATE_RECURRING_ENDPOINT =
  '/ajxapi/create_cp_order/emandate';
const CUSTOMER_RAZORPAY_PAYMENT_API_CARD_RECURRING_ENDPOINT =
  '/ajxapi/create_cp_order/card';
const CUSTOMER_RAZORPAY_PAYMENT_API_UPI_RECURRING_ENDPOINT =
  '/ajxapi/create_cp_order/upi';
const EAZY_PAYMENT_API_RECURRING_ENDPOINT = '/ajxapi/register_mandate/upi';
const EAZY_PAYMENT_API_EMANDATE_RECURRING_ENDPOINT =
  '/ajxapi/register_mandate/emandate';
const EAZY_PAYMENT_API_UPI_RECURRING_ENDPOINT = '/ajxapi/register_mandate/upi';
const EAZY_PAYMENT_SUCCESS_ENDPOINT = '/ajxapi/save_mandate_response';
const EAZY_PAYMENT_NACH_SUCCESS_ENDPOINT = '/ajxapi/register_papernach';
const CUSTOMER_PAYMENT_REDEEM_COINS_ENDPOINT = '/v1/user/redeemcfcoins';
const CUSTOMER_PAYMENT_REMOVE_COINS_ENDPOINT = '/v1/user/removecfcoins';
const HOME_SCREEN_ENDPOINT = '/v1/common/home';
const GET_CHANGE_TYPE_PAYMENT_MODE_ENDPOINT = '/v1/user/changepaymentmode';
const CHANGE_PAYMENT_MODE_ENDPOINT = '/v1/user/savechangepaymentmode';
const FACEBOOK_USER_ENDPOINT =
  'https://graph.facebook.com/me?fields=id,name,email&access_token=';
const UPDATE_FCM_DEVICE_TOKEN_ENDPOINT = '/v1/user/updatedevicetoken';
const ADD_CF_COIN_ENDPOINT = '/v1/user/addcoins';
const USER_SERVICE_REQUEST_ENDPOINT = '/v1/user/userservicerequests';
const HOW_IT_WORK_QA_ENDPOINT = '/v1/common/howitworks';
const GET_APPLE_LOGIN_RESPONSE_ENDPOINT = '/v1/user/getappleresponse';
const GET_UPDATE_WALLET_AMOUNT_ENDPOINT = '/v1/user/updatewalletamount';
const VERIFY_CRIF_ANSWER_ENDPOINT = '/v1/user/verifycrifanswer';
const GET_APP_LIVE_VERSION_ENDPOINT = '/v1/common/getappversion';
const VALIDATE_CART_ENDPOINT = '/v1/cart/validatecart';
const FEEDBACK_ENDPOINTS = '/ajxapi/save_feedback';
const FEEDBACK_URL_ENDPOINTS = '/ajxapi/get_feedback_url_details';
const USER_NOTIFICATION_ENDPOINT = '/ajxapi/get_app_notifications_list';
const UPDATE_CONTACT_ENDPOINT = '/ajxapi/save_app_user_contacts';
const GET_NON_SERVICEABLE_POSTALCODE_ENDPOINT =
  '/ajxapi/non_serviceable_postalcode';
const FRP_FAQ_ENDPOINT = '/ajxapi/frp_faq_details';
const FRP_HOW_ITS_WORKS_ENDPOINT = '/ajxapi/frp_how_its_works_details';
const FRP_FURNISHING_PLAN_ENDPOINT = '/ajxapi/frp_furnishing_plan_details';
const GET_FIRST_RUNNING_ORDER_ENDPOINTS = '/v1/user/getallorders';
const ENQUIRE_CHATBOT_QUERY_REQUEST_ENDPOINTS =
  '/ajxapi/save_chatbot_query_request';
const HOME_ENDPOINT = '/v1/common/home'
export default function ApiEndpoint(type) {
  switch (type) {
    
    case TRENDING_PRODUCT_API:
      return `${BASE_URL}${HOME_ENDPOINT}`;
    case SIGNUP_API:
      return `${BASE_URL}${SIGNUP_ENDPOINT}`;
    case LOGIN_API:
      return `${BASE_URL}${LOGIN_ENDPOINT}`;
    case SEND_OTP_API:
      return `${BASE_URL}${SEND_OTP_ENDPOINT}`;
    case VERIFY_OTP_AND_LOGIN_API:
      return `${BASE_URL}${VERIFY_OTP_AND_LOGIN_ENDPOINT}`;
    case SOCIAL_LOGIN_API:
      return `${BASE_URL}${SOCIAL_LOGIN_ENDPOINT}`;
    case UPDATE_PROFILE_API:
      return `${BASE_URL}${UPDATE_PROFILE_ENDPOINT}`;
    case GET_USER_PROFILE_API:
      return `${BASE_URL}${GET_USER_PROFILE_ENDPOINT}`;
    case VERIFY_MOBILE_NUMBER_API:
      return `${BASE_URL}${VERIFY_MOBILE_NUMBER_ENDPOINT}`;
    case VERIFY_EMAIL_API:
      return `${BASE_URL}${VERIFY_EMAIL_ENDPOINT}`;
    case GET_ALL_CITIES_API:
      return `${BASE_URL}${ALL_CITIES_ENDPOINT}`;
    case CHANGE_PASSWORD_API:
      return `${BASE_URL}${CHANGE_PASSWORD_ENDPOINT}`;
    case VERIFY_OTP_ONLY_API:
      return `${BASE_URL}${VERIFY_OTP_ONLY_ENDPOINT}`;
    case LINKEDIN_USER_API:
      return `${LINKEDIN_USER_ENDPOINT}`;
    case DIRECT_SOCIAL_LOGIN_API:
      return `${BASE_URL}${DIRECT_SOCIAL_LOGIN_ENDPOINT}`;
    case ALL_PRODUCT_DETAIL_API:
      return `${BASE_URL}${GET_ALL_PRODUCT_DETAIL_ENDPOINT}`;
    case GET_OFFERS_API:
      return `${BASE_URL}${GET_OFFERS_ENDPOINT}`;
    case CATEGORY_LISTING_API:
      return `${BASE_URL}${CATEGORY_LISTING_ENDPOINTS}`;
    case ADD_ADDRESS_API:
      return `${BASE_URL}${ADD_ADDRESS_ENDPOINTS}`;
    case ADDRESS_LISTING_API:
      return `${BASE_URL}${ADDRESS_LISTING_ENDPOINTS}`;
    case REVIEW_LISTING_API:
      return `${BASE_URL}${REVIEW_LISTING_ENDPOINTS}`;
    case GET_ALL_WISHLIST:
      return `${BASE_URL}${GET_ALL_WISHLIST_ENDPOINTS}`;
    case GET_PRODUCT_LISTING_API:
      return `${BASE_URL}${GET_PRODUCT_LISTING_API_ENDPOINTS}`;
    case ADD_DELETE_WISHLIST_API:
      return `${BASE_URL}${ADD_DELETE_WISHLIST_API_ENDPOINTS}`;
    case GET_FILTER_LISTING_API:
      return `${BASE_URL}${GET_FILTER_LISTING_ENDPOINTS}`;
    case DELETE_ADDRESS_API:
      return `${BASE_URL}${DELETE_ADDRESS_ENDPOINTS}`;
    case GET_STATE_CITY_API:
      return `${BASE_URL}${GET_STATE_CITY_ENDPOINT}`;
    case GET_INVOICES_API:
      return `${BASE_URL}${GET_INVOICES_ENDPOINTS}`;
    case ADD_TO_CART_API:
      return `${BASE_URL}${ADD_TO_CART_ENDPOINTS}`;
    case GET_CART_DETAIL_API:
      return `${BASE_URL}${GET_CART_DETAIL_ENDPOINTS}`;
    case SEARCH_PRODUCT_API:
      return `${BASE_URL}${SEARCH_PRODUCT_ENDPOINTS}`;
    case GET_REFERRAL_CODE_API:
      return `${BASE_URL}${GET_REFERRAL_CODE_ENDPOINT}`;
    case DELETE_FROM_CART_API:
      return `${BASE_URL}${DELETE_FROM_CART_ENDPOINT}`;
    case DELETE_COUPON_CODE_API:
      return `${BASE_URL}${DELETE_COUPON_CODE_ENDPOINT}`;
    case APPLY_COUPON_CODE_API:
      return `${BASE_URL}${APPLY_COUPON_CODE_ENDPOINT}`;
    case CORPORATE_ORDER_API:
      return `${BASE_URL}${CORPORATE_ORDER_ENDPOINT}`;
    case CORPORATE_ORDER_DETAILS_API:
      return `${BASE_URL}${CORPORATE_ORDER_DETAILS_ENDPOINTS}`;
    case DEFAULT_ADDRESS_API:
      return `${BASE_URL}${DEFAULT_ADDRESS_ENDPOINTS}`;
    case GET_FRP_PLANS_API:
      return `${BASE_URL}${GET_FRP_PLANS_ENDPOINTS}`;
    case GET_CBIL_DOCUMENTS_API:
      return `${BASE_URL}${GET_CBIL_DOCUMENTS_ENDPOINTS}`;
    case GET_ALL_ORDER_API:
      return `${BASE_URL}${GET_ALL_ORDER_ENDPOINTS}`;
    case GET_FIRST_RUNNING_ORDER_API:
      return `${BASE_URL}${GET_FIRST_RUNNING_ORDER_ENDPOINTS}`;
    case GET_ALL_SCHEDULED_ORDER_API:
      return `${BASE_URL}${GET_ALL_SCHEDULED_ORDER_ENDPOINTS}`;
    case VERIFY_CREDIT_SCORE_API:
      return `${BASE_URL}${VERIFY_CREDIT_SCORE_ENDPOINTS}`;
    case GET_KYC_SCORE_API:
      return `${BASE_URL}${GET_KYC_SCORE_ENDPOINTS}`;
    case SAVE_KYC_DATA_API:
      return `${BASE_URL}${SAVE_KYC_DATA_ENDPOINTS}`;
    case UPLOAD_KYC_DATA_API:
      return `${BASE_URL}${UPLOAD_KYC_DATA_ENDPOINTS}`;
    case NOTIFY_PRODCUT_API:
      return `${BASE_URL}${NOTIFY_PRODCUT_ENDPOINT}`;
    case GET_FRP_PLAN_DETAIL_API:
      return `${BASE_URL}${GET_FRP_PLAN_DETAIL_ENDPOINT}`;
    case GET_FRP_SUGGESTION_PRODUCTS_API:
      return `${BASE_URL}${GET_FRP_SUGGESTION_PRODUCTS_ENDPOINT}`;
    case ADD_FRP_PRODUCT_TO_CART_API:
      return `${BASE_URL}${ADD_FRP_PRODUCT_TO_CART_ENDPOINT}`;
    case GENERATE_HASH_API:
      return `${BASE_URL}${GENERATE_HASH_ENDPOINT}`;
    case GET_CMS_PAGE_DETAIL_API:
      return `${BASE_URL}${GET_CMS_PAGE_DETAIL_ENDPOINT}`;
    case GET_VIEW_ORDER_DETAIL_API:
      return `${BASE_URL}${GET_VIEW_ORDER_DETAIL_ENDPOINT}`;
    case CART_CHECKOUT_API:
      return `${BASE_URL}${CART_CHECKOUT_ENDPOINT}`;
    case CART_CHECKOUT_INITATION_API:
      return `${BASE_URL}${CART_CHECKOUT_INITATION_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_API:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_API_EMANDATE_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_EMANDATE_RECURRING_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_API_CARD_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_CARD_RECURRING_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_API_UPI_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_UPI_RECURRING_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_SUCCESS_API:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_SUCCESS_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_SUCCESS_API_EMANDATE_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_SUCCESS_EMANDATE_RECURRING_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_SUCCESS_API_CARD_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_SUCCESS_CARD_RECURRING_ENDPOINT}`;
    case CART_CHECKOUT_RAZORPAY_SUCCESS_API_UPI_RECURRING:
      return `${BASE_URL}${CART_CHECKOUT_RAZORPAY_SUCCESS_UPI_RECURRING_ENDPOINT}`;
    case GET_PAYMENT_INFO_API:
      return `${BASE_URL}${GET_PAYMENT_INFO_ENDPOINT}`;
    case GET_MY_PAYMENT_API:
      return `${BASE_URL}${GET_MY_PAYMENT_ENDPOINTS}`;
    case GET_CF_COINS_DETAIL_API:
      return `${BASE_URL}${GET_CF_COINS_DETAIL_ENDPOINTS}`;
    case GET_MANAGE_SERVICE_REQUET_API:
      return `${BASE_URL}${GET_MANAGE_SERVICE_REQUET_ENDPOINTS}`;
    case GET_MANAGE_SERVICE_REQUEST_POST_API:
      return `${BASE_URL}${GET_MANAGE_SERVICE_REQUEST_POST_ENDPOINTS}`;
    case DOWNLOAD_PAYMENT_STATEMENT_API:
      return `${BASE_URL}${DOWNLOAD_PAYMENT_STATEMENT_ENDPOINTS}`;
    case ENQUIRE_OFFICE_FURNITURE_API:
      return `${BASE_URL}${ENQUIRE_OFFICE_FURNITURE_ENDPOINTS}`;
    case CHATBOT_QUERY_REQUEST_API:
      return `${BASE_URL}${ENQUIRE_CHATBOT_QUERY_REQUEST_ENDPOINTS}`;
    case FEEDBACK_API:
      return `${BASE_URL}${FEEDBACK_ENDPOINTS}`;
    case FEEDBACK_URL_API:
      return `${BASE_URL}${FEEDBACK_URL_ENDPOINTS}`;
    case GET_FAQ_PAGE_DETAIL_API:
      return `${BASE_URL}${GET_FAQ_PAGE_DETAIL_ENDPOINT}`;
    case SEND_SERVICE_REQUEST_API:
      return `${BASE_URL}${SEND_SERVICE_REQUEST_ENDPOINT}`;
    case REDEEM_COINS_API:
      return `${BASE_URL}${REDEEM_COINS_ENDPOINT}`;
    case WALLET_TOPUP_API:
      return `${BASE_URL}${WALLET_TOPUP_ENDPOINT}`;
    case INVOICE_PAYMENT_API:
      return `${BASE_URL}${INVOICE_PAYMENT_ENDPOINT}`;
    case INVOICE_REMOVE_COINS_API:
      return `${BASE_URL}${INVOICE_REMOVE_COINS_ENDPOINT}`;
    case INVOICE_REDEEM_COINS_API:
      return `${BASE_URL}${INVOICE_REDEEM_COINS_ENDPOINT}`;
    case CUSTOMER_PAYMENT_API:
      return `${BASE_URL}${CUSTOMER_PAYMENT_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_API:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_ENDPOINT}`;
    case CREATE_CUSTOMER_RAZORPAY_PAYMENT_API:
      return `${BASE_URL}${CREATE_CUSTOMER_RAZORPAY_PAYMENT_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_SUCCESS_API:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_SUCCESS_ENDPOINT}`;
    case CREATE_OUTSTANDING_RAZORPAY_PAYMENT_API:
      return `${BASE_URL}${CREATE_OUTSTANDING_RAZORPAY_PAYMENT_ENDPOINT}`;
    case OUTSTANDING_RAZORPAY_PAYMENT_SUCCESS_API:
      return `${BASE_URL}${OUTSTANDING_RAZORPAY_PAYMENT_SUCCESS_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_API_RECURRING:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_RECURRING_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_API_EMANDATE_RECURRING:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_API_EMANDATE_RECURRING_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_API_CARD_RECURRING:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_API_CARD_RECURRING_ENDPOINT}`;
    case CUSTOMER_RAZORPAY_PAYMENT_API_UPI_RECURRING:
      return `${BASE_URL}${CUSTOMER_RAZORPAY_PAYMENT_API_UPI_RECURRING_ENDPOINT}`;
    case EAZY_PAYMENT_API_EMANDATE_RECURRING:
      return `${BASE_URL}${EAZY_PAYMENT_API_EMANDATE_RECURRING_ENDPOINT}`;
    case EAZY_PAYMENT_API_UPI_RECURRING:
      return `${BASE_URL}${EAZY_PAYMENT_API_UPI_RECURRING_ENDPOINT}`;
    case EAZY_PAYMENT_API_RECURRING:
      return `${BASE_URL}${EAZY_PAYMENT_API_RECURRING_ENDPOINT}`;
    case EAZY_PAYMENT_SUCCESS_API:
      return `${BASE_URL}${EAZY_PAYMENT_SUCCESS_ENDPOINT}`;
    case EAZY_PAYMENT_NACH_SUCCESS_API:
      return `${BASE_URL}${EAZY_PAYMENT_NACH_SUCCESS_ENDPOINT}`;
    case CUSTOMER_PAYMENT_REMOVE_COINS_API:
      return `${BASE_URL}${CUSTOMER_PAYMENT_REMOVE_COINS_ENDPOINT}`;
    case CUSTOMER_PAYMENT_REDEEM_COINS_API:
      return `${BASE_URL}${CUSTOMER_PAYMENT_REDEEM_COINS_ENDPOINT}`;
    case HOME_SCREEN_API:
      return `${BASE_URL}${HOME_SCREEN_ENDPOINT}`;
    case GET_CHANGE_TYPE_PAYMENT_MODES_API:
      return `${BASE_URL}${GET_CHANGE_TYPE_PAYMENT_MODE_ENDPOINT}`;
    case CHANGE_PAYMENT_MODE_API:
      return `${BASE_URL}${CHANGE_PAYMENT_MODE_ENDPOINT}`;
    case FACEBOOK_USER_API:
      return `${FACEBOOK_USER_ENDPOINT}`;
    case UPDATE_CONTACT_API:
      return `${BASE_URL}${UPDATE_CONTACT_ENDPOINT}`;
    case UPDATE_FCM_DEVICE_TOKEN_API:
      return `${BASE_URL}${UPDATE_FCM_DEVICE_TOKEN_ENDPOINT}`;
    case ADD_CF_COIN_API:
      return `${BASE_URL}${ADD_CF_COIN_ENDPOINT}`;
    case USER_SERVICE_REQUEST_API:
      return `${BASE_URL}${USER_SERVICE_REQUEST_ENDPOINT}`;
    case USER_NOTIFICATION_API:
      return `${BASE_URL}${USER_NOTIFICATION_ENDPOINT}`;
    case HOW_IT_WORK_QA_API:
      return `${BASE_URL}${HOW_IT_WORK_QA_ENDPOINT}`;
    case FRP_FAQ_API:
      return `${BASE_URL}${FRP_FAQ_ENDPOINT}`;
    case FRP_HOW_ITS_WORKS_API:
      return `${BASE_URL}${FRP_HOW_ITS_WORKS_ENDPOINT}`;
    case FRP_FURNISHING_PLAN_API:
      return `${BASE_URL}${FRP_FURNISHING_PLAN_ENDPOINT}`;
    case GET_APPLE_LOGIN_RESPONSE_API:
      return `${BASE_URL}${GET_APPLE_LOGIN_RESPONSE_ENDPOINT}`;
    case GET_UPDATE_WALLET_AMOUNT_API:
      return `${BASE_URL}${GET_UPDATE_WALLET_AMOUNT_ENDPOINT}`;
    case VERIFY_CRIF_ANSWER_API:
      return `${BASE_URL}${VERIFY_CRIF_ANSWER_ENDPOINT}`;
    case GET_APP_LIVE_VERSION_API:
      return `${BASE_URL}${GET_APP_LIVE_VERSION_ENDPOINT}`;
    case GET_NON_SERVICEABLE_POSTALCODE_API:
      return `${BASE_URL}${GET_NON_SERVICEABLE_POSTALCODE_ENDPOINT}`;
    case VALIDATE_CART_API:
      return `${BASE_URL}${VALIDATE_CART_ENDPOINT}`;
    default:
      return '';
  }
}
