import {StyleSheet} from 'react-native';
import resources from '../../../../res';
import {isPlatformIOS, myWidth} from '../../../utility/Utils';
const styles = StyleSheet.create({
  fullScreen: {
    flex: 1,
    backgroundColor: resources.colors.white,
  },
  textOrderDetails: {
    fontFamily: resources.fonts.regular,
    fontSize: 19,
    fontWeight: '600',
    marginBottom: 8,
    color: resources.colors.textBlack,
  },
  detailCard: {
    // flex: 1,
    // height: isPlatformIOS ? 285 : heightScale(330),
    width: '100%',
    marginTop: 10,
    backgroundColor: resources.colors.white,
    flexDirection: 'row',
    borderRadius: 6,
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 4,
    shadowOpacity: 0.3,
    elevation: 6,
  },
  detailSavingCard: {
    // flex: 1,
    // height: isPlatformIOS ? 285 : heightScale(330),
    width: '100%',
    marginTop: 10,
    backgroundColor: resources.colors.white,
    borderWidth: 1,
    borderColor: 'green',
    borderStyle: 'dashed',
    flexDirection: 'row',
    borderRadius: 6,
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 4,
    shadowOpacity: 0.3,
    elevation: 6,
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  orderCardContainer: {
    flex: 1,
  },
  orderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  orderPropText: {
    fontFamily: resources.fonts.regular,
    fontSize: 13,
    color: resources.colors.textBlack,
    marginTop: 12,
  },
  orderPropOffText: {
    fontFamily: resources.fonts.bold,
    fontSize: 13,
    backgroundColor: 'green',
    color: resources.colors.white,
    marginTop: 12,
    textAlign: 'center',
    paddingHorizontal: 5,
    marginHorizontal: 10,
    borderRadius: 2,
  },
  orderValuesText: {
    fontFamily: resources.fonts.regular,
    fontSize: 13,
    color: resources.colors.textBlack,
    marginTop: 12,
    alignSelf: 'flex-end',
  },
  seprator1: {
    height: 1,
    width: '100%',
    backgroundColor: resources.colors.greyLight,
  },
  totalContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
    height: 40,
    marginBottom: 5,
    marginTop: 4,
    borderTopWidth: 1,
    borderColor: 'rgba(54,69,79,0.5)',
  },
  totalTextStyle: {
    fontFamily: resources.fonts.bold,
    fontSize: 12,
    color: resources.colors.textBlack,
    marginTop: 10,
  },
  emiTextStyle: {
    fontFamily: resources.fonts.bold,
    fontSize: 12,
    backgroundColor: resources.colors.grassGreen,
    color: resources.colors.white,
    marginTop: 4,
    paddingVertical: 6,
    marginHorizontal: 10,
    textAlign: 'center',
    borderRadius: 8,
  },
  parentContainer: {
    flex: 1,
    marginHorizontal: 20,
    marginVertical: 20,
    marginTop: 20,
    marginBottom: 100,
  },
  textcfCoinLabel: {
    fontFamily: resources.fonts.regular,
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 12,
    color: resources.colors.labelColor,
  },
  cfBalanceView: {marginTop: 20, borderWidth: 0},
  coinsView: {flexDirection: 'row', alignItems: 'center'},
  rowDirection: {flexDirection: 'row'},
  textCFBalance: {
    color: resources.colors.charcoalGrey,
    fontSize: 17,
    fontFamily: resources.fonts.regular,
    fontWeight: '600',
    alignSelf: 'center',
    marginLeft: 5,
  },
  textTotalCoins: {
    color: resources.colors.txtGetOTP,
    fontSize: 18,
    fontFamily: resources.fonts.bold,
  },
  coinsInput: {
    borderBottomWidth: 1,
    fontSize: 18,
    color: resources.colors.labelColor,
    borderBottomColor: resources.colors.labelColor,
  },
  btnStyle: {borderRadius: 8, width: 170, height: 43},
  btnTouchStyle: {
    marginTop: 24,
    borderRadius: 8,
    width: 170,
    alignSelf: 'center',
  },
  textInstruction: {
    color: resources.colors.textBlack,
    fontFamily: resources.fonts.regular,
    fontSize: 13,
    marginBottom: 4,
    marginTop: 5,
  },
  viewGST: {borderWidth: 0},
  textGstDetails: {
    fontFamily: resources.fonts.regular,
    fontSize: 19,
    fontWeight: '600',
    color: resources.colors.textBlack,
    borderWidth: 0,
    marginVertical: 17,
  },
  whatappToggleStyle: {
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 7,
  },
  whatappToggleText: {
    color: resources.colors.labelColor,
    fontFamily: resources.fonts.bold,
    fontSize: 16,
  },
  gstcheckbox: {
    width: 20,
    height: 20,
    borderColor: resources.colors.labelColor,
  },
  textIhaveGst: {
    color: resources.colors.labelColor,
    fontFamily: resources.fonts.regular,
    fontSize: 14,
    marginLeft: 15,
  },
  viewPaymentMethods: {marginVertical: 5},
  containerHeight: {
    paddingVertical: 10,
    marginTop: 15,
    backgroundColor: resources.colors.white,
    shadowColor: '#000000',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    borderRadius: 6,
  },
  cardNameStyle: {
    marginLeft: 21,
    fontFamily: resources.fonts.regular,
    fontWeight: '600',
    color: resources.colors.labelColor,
    fontSize: 15,
    alignSelf: 'center',
  },
  iconStyle: {
    height: 38,
    width: 38,
  },
  creditCardView: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
    paddingHorizontal: 20,
  },
  textChoosePaymentMethod: {
    color: resources.colors.labelColor,
    fontFamily: resources.fonts.regular,
    fontSize: 14,
  },
  addressButtonContainer: {
    flex: 1,
    // flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    width: '100%',
    borderTopColor: 'rgba(10,36,99,0.1)',
    alignItems: 'center',
    height: isPlatformIOS ? 75 : 65,
    backgroundColor: resources.colors.white,
    position: 'absolute',
    bottom: 0,
    zIndex: 9999,
    paddingHorizontal: 20,
  },
  addressFooterStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  stylePriceSection: {
    // height: heightScale(48),
    width: myWidth / 2 - 20,
    marginTop: 10,
    height: 48,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: resources.colors.appColor,
    color: resources.colors.appColor,
    alignSelf: 'stretch',
    marginBottom: isPlatformIOS ? 15 : 10,
    borderRadius: 4,
  },
  proceedSection: {
    // width: 140,
    width: myWidth - 30,
    marginTop: 10,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: resources.colors.appColor,
    color: resources.colors.white,
    alignSelf: 'stretch',
    marginBottom: isPlatformIOS ? 5 : 10,
    borderRadius: 4,
  },
  footerStyleColumn: {
    flex: 1,
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: 30,
    marginLeft: 0,
  },
  footerStyle: {
    flex: 1,
    // alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    marginRight: 10,
    marginLeft: 10,
  },
  chooseDuration: {
    textAlign: 'center',
    fontSize: 18,
    // justifyContent: 'center',
    // alignItems: 'center',
    color: 'rgb(28,28,28)',
    fontFamily: resources.fonts.regular,
    fontWeight: '600',
  },
  totalStyle: {
    color: 'rgb(45,109,154)',
    fontSize: 20,
    fontFamily: resources.fonts.bold,
    fontWeight: '600',
    textAlign: 'left',
    // justifyContent: 'center',
    // alignItems: 'center',
    marginTop: isPlatformIOS ? 10 : 0,
    flex: 1,
  },
  descStyle: {
    color: 'rgb(45,109,154)',
    fontSize: 13,
    fontFamily: resources.fonts.regular,
    textAlign: 'left',
    flex: 1,
    marginLeft: 10,
    marginTop: isPlatformIOS ? 10 : 0,
  },
  lineStyle: {
    borderWidth: 1,
    borderColor: resources.colors.appColor,
    margin: 0,
    width: 50,
    marginBottom: 10,
  },
  orderRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 0,
    paddingLeft: 10,
    paddingVertical: 6,
  },
  saveRowContainer: {
    flexDirection: 'row',
    marginHorizontal: 0,
  },
  row: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: 5,
    borderWidth: 0,
    marginHorizontal: 20,
    // backgroundColor: '#dddddd'
  },
  cellStyle: {
    flex: 1,
    marginRight: 10,
  },
  userNameText: {
    fontFamily: resources.fonts.bold,
    color: resources.colors.black,
    fontSize: 14,
  },
  fontStyle: {
    fontFamily: resources.fonts.bold,
    fontSize: 12,
    color: resources.colors.appColor,
    lineHeight: 18,
  },
  defaultTxt: {
    fontFamily: resources.fonts.bold,
    fontSize: 11,
  },
  viewEdit: {
    // width: '25%',
    marginTop: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  offerTextStyle: {
    fontSize: 11,
    lineHeight: 15,
    fontFamily: resources.fonts.regular,
    fontWeight: '500',
    marginTop: 5,
  },
  buttonStyle: {
    width: 80,
    height: 36,
    borderRadius: 6,
  },
  btnTextStyle: {
    color: resources.colors.white,
    fontSize: 12,
    fontFamily: resources.fonts.regular,
    // borderWidth:1,
    textAlign: 'center',
  },
  upfrontBox: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: 6,
    borderRadius: 6,
    // height: 131,
    // paddingHorizontal: 10,
    backgroundColor: 'white',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  linearGradient: {
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
});

export default styles;
